// Code generated by Fern. DO NOT EDIT.

package email

import (
	context "context"
	os "os"

	osintcat "github.com/OsintCatHQ/osintcat-go"
	core "github.com/OsintCatHQ/osintcat-go/core"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	option "github.com/OsintCatHQ/osintcat-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("OSINTCAT_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Checks which websites and services an e-mail address is registered with and in which breaches it appears. Every request must state its purpose.
//
// A request without a purpose (parameter `purpose`, header `X-Purpose`, or `Purpose: ...` at the end of your User-Agent) is refused with `400 USER_AGENT_IDENTITY_REQUIRED`.
//
// Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.
//
// Errors:
// - 400 `USER_AGENT_IDENTITY_REQUIRED`: No purpose given.
// - 401 `API key required`: No `X-API-KEY` header.
// - 402 `INSUFFICIENT_BALANCE`: The allowance is used up and your balance does not cover the lookup.
// - 424 `Provider Error`: The lookup could not be completed. Not charged.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/email-osint
func (c *Client) Lookup(
	ctx context.Context,
	request *osintcat.LookupEmailRequest,
	opts ...option.RequestOption,
) (*osintcat.EmailOsintResponse, error) {
	response, err := c.WithRawResponse.Lookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
