// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	modulesModulesFieldID           = big.NewInt(1 << 0)
	modulesModulesFieldName         = big.NewInt(1 << 1)
	modulesModulesFieldCategory     = big.NewInt(1 << 2)
	modulesModulesFieldEnabled      = big.NewInt(1 << 3)
	modulesModulesFieldAccessLevel  = big.NewInt(1 << 4)
	modulesModulesFieldAllowedPlans = big.NewInt(1 << 5)
	modulesModulesFieldAccessible   = big.NewInt(1 << 6)
	modulesModulesFieldLocked       = big.NewInt(1 << 7)
)

type ModulesModules struct {
	// Module id.
	ID *string `json:"id,omitempty" url:"id,omitempty"`
	// Display name.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Category it is listed under.
	Category *string `json:"category,omitempty" url:"category,omitempty"`
	// Whether the module is switched on.
	Enabled *bool `json:"enabled,omitempty" url:"enabled,omitempty"`
	// `public`, `beta`, `staff` or `nobody`.
	AccessLevel *string `json:"access_level,omitempty" url:"access_level,omitempty"`
	// Plans the module is limited to (empty: all plans).
	AllowedPlans []any `json:"allowed_plans,omitempty" url:"allowed_plans,omitempty"`
	// Whether your account can use it right now.
	Accessible *bool `json:"accessible,omitempty" url:"accessible,omitempty"`
	// Shown, but not usable on your plan.
	Locked *bool `json:"locked,omitempty" url:"locked,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (m *ModulesModules) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *ModulesModules) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *ModulesModules) GetCategory() *string {
	if m == nil {
		return nil
	}
	return m.Category
}

func (m *ModulesModules) GetEnabled() *bool {
	if m == nil {
		return nil
	}
	return m.Enabled
}

func (m *ModulesModules) GetAccessLevel() *string {
	if m == nil {
		return nil
	}
	return m.AccessLevel
}

func (m *ModulesModules) GetAllowedPlans() []any {
	if m == nil {
		return nil
	}
	return m.AllowedPlans
}

func (m *ModulesModules) GetAccessible() *bool {
	if m == nil {
		return nil
	}
	return m.Accessible
}

func (m *ModulesModules) GetLocked() *bool {
	if m == nil {
		return nil
	}
	return m.Locked
}

func (m *ModulesModules) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.ExtraProperties
}

func (m *ModulesModules) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesModules) SetID(id *string) {
	m.ID = id
	m.require(modulesModulesFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesModules) SetName(name *string) {
	m.Name = name
	m.require(modulesModulesFieldName)
}

// SetCategory sets the Category field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesModules) SetCategory(category *string) {
	m.Category = category
	m.require(modulesModulesFieldCategory)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesModules) SetEnabled(enabled *bool) {
	m.Enabled = enabled
	m.require(modulesModulesFieldEnabled)
}

// SetAccessLevel sets the AccessLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesModules) SetAccessLevel(accessLevel *string) {
	m.AccessLevel = accessLevel
	m.require(modulesModulesFieldAccessLevel)
}

// SetAllowedPlans sets the AllowedPlans field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesModules) SetAllowedPlans(allowedPlans []any) {
	m.AllowedPlans = allowedPlans
	m.require(modulesModulesFieldAllowedPlans)
}

// SetAccessible sets the Accessible field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesModules) SetAccessible(accessible *bool) {
	m.Accessible = accessible
	m.require(modulesModulesFieldAccessible)
}

// SetLocked sets the Locked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesModules) SetLocked(locked *bool) {
	m.Locked = locked
	m.require(modulesModulesFieldLocked)
}

func (m *ModulesModules) UnmarshalJSON(data []byte) error {
	type embed ModulesModules
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = ModulesModules(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.ExtraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *ModulesModules) MarshalJSON() ([]byte, error) {
	type embed ModulesModules
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, m.ExtraProperties)
}

func (m *ModulesModules) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	modulesResponseFieldModules = big.NewInt(1 << 0)
	modulesResponseFieldUser    = big.NewInt(1 << 1)
)

type ModulesResponse struct {
	// One entry per module.
	Modules []*ModulesModules `json:"modules,omitempty" url:"modules,omitempty"`
	User    *ModulesUser      `json:"user,omitempty" url:"user,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (m *ModulesResponse) GetModules() []*ModulesModules {
	if m == nil {
		return nil
	}
	return m.Modules
}

func (m *ModulesResponse) GetUser() *ModulesUser {
	if m == nil {
		return nil
	}
	return m.User
}

func (m *ModulesResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.ExtraProperties
}

func (m *ModulesResponse) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetModules sets the Modules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesResponse) SetModules(modules []*ModulesModules) {
	m.Modules = modules
	m.require(modulesResponseFieldModules)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesResponse) SetUser(user *ModulesUser) {
	m.User = user
	m.require(modulesResponseFieldUser)
}

func (m *ModulesResponse) UnmarshalJSON(data []byte) error {
	type embed ModulesResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = ModulesResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.ExtraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *ModulesResponse) MarshalJSON() ([]byte, error) {
	type embed ModulesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, m.ExtraProperties)
}

func (m *ModulesResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	modulesUserFieldPlan       = big.NewInt(1 << 0)
	modulesUserFieldRole       = big.NewInt(1 << 1)
	modulesUserFieldBetaAccess = big.NewInt(1 << 2)
)

type ModulesUser struct {
	// Plan id.
	Plan *string `json:"plan,omitempty" url:"plan,omitempty"`
	// Account role.
	Role *string `json:"role,omitempty" url:"role,omitempty"`
	// Whether the account has beta access.
	BetaAccess *bool `json:"beta_access,omitempty" url:"beta_access,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (m *ModulesUser) GetPlan() *string {
	if m == nil {
		return nil
	}
	return m.Plan
}

func (m *ModulesUser) GetRole() *string {
	if m == nil {
		return nil
	}
	return m.Role
}

func (m *ModulesUser) GetBetaAccess() *bool {
	if m == nil {
		return nil
	}
	return m.BetaAccess
}

func (m *ModulesUser) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.ExtraProperties
}

func (m *ModulesUser) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetPlan sets the Plan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesUser) SetPlan(plan *string) {
	m.Plan = plan
	m.require(modulesUserFieldPlan)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesUser) SetRole(role *string) {
	m.Role = role
	m.require(modulesUserFieldRole)
}

// SetBetaAccess sets the BetaAccess field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModulesUser) SetBetaAccess(betaAccess *bool) {
	m.BetaAccess = betaAccess
	m.require(modulesUserFieldBetaAccess)
}

func (m *ModulesUser) UnmarshalJSON(data []byte) error {
	type embed ModulesUser
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = ModulesUser(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.ExtraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *ModulesUser) MarshalJSON() ([]byte, error) {
	type embed ModulesUser
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, m.ExtraProperties)
}

func (m *ModulesUser) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	userAccountInfoFieldUsername    = big.NewInt(1 << 0)
	userAccountInfoFieldEmail       = big.NewInt(1 << 1)
	userAccountInfoFieldPlan        = big.NewInt(1 << 2)
	userAccountInfoFieldPlanExpires = big.NewInt(1 << 3)
)

type UserAccountInfo struct {
	// Username.
	Username *string `json:"username,omitempty" url:"username,omitempty"`
	// E-mail address of the account.
	Email *string `json:"email,omitempty" url:"email,omitempty"`
	// Current plan, e.g. `Researcher`, `Investigator`, `Max`.
	Plan *string `json:"plan,omitempty" url:"plan,omitempty"`
	// When the plan ends (ISO 8601), `Lifetime`, or `N/A`.
	PlanExpires *string `json:"plan_expires,omitempty" url:"plan_expires,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (u *UserAccountInfo) GetUsername() *string {
	if u == nil {
		return nil
	}
	return u.Username
}

func (u *UserAccountInfo) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UserAccountInfo) GetPlan() *string {
	if u == nil {
		return nil
	}
	return u.Plan
}

func (u *UserAccountInfo) GetPlanExpires() *string {
	if u == nil {
		return nil
	}
	return u.PlanExpires
}

func (u *UserAccountInfo) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.ExtraProperties
}

func (u *UserAccountInfo) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserAccountInfo) SetUsername(username *string) {
	u.Username = username
	u.require(userAccountInfoFieldUsername)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserAccountInfo) SetEmail(email *string) {
	u.Email = email
	u.require(userAccountInfoFieldEmail)
}

// SetPlan sets the Plan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserAccountInfo) SetPlan(plan *string) {
	u.Plan = plan
	u.require(userAccountInfoFieldPlan)
}

// SetPlanExpires sets the PlanExpires field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserAccountInfo) SetPlanExpires(planExpires *string) {
	u.PlanExpires = planExpires
	u.require(userAccountInfoFieldPlanExpires)
}

func (u *UserAccountInfo) UnmarshalJSON(data []byte) error {
	type embed UserAccountInfo
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UserAccountInfo(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.ExtraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserAccountInfo) MarshalJSON() ([]byte, error) {
	type embed UserAccountInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, u.ExtraProperties)
}

func (u *UserAccountInfo) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	userResponseFieldAccountInfo = big.NewInt(1 << 0)
	userResponseFieldUsage       = big.NewInt(1 << 1)
)

type UserResponse struct {
	AccountInfo *UserAccountInfo `json:"account_info,omitempty" url:"account_info,omitempty"`
	Usage       *UserUsage       `json:"usage,omitempty" url:"usage,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (u *UserResponse) GetAccountInfo() *UserAccountInfo {
	if u == nil {
		return nil
	}
	return u.AccountInfo
}

func (u *UserResponse) GetUsage() *UserUsage {
	if u == nil {
		return nil
	}
	return u.Usage
}

func (u *UserResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.ExtraProperties
}

func (u *UserResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAccountInfo sets the AccountInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserResponse) SetAccountInfo(accountInfo *UserAccountInfo) {
	u.AccountInfo = accountInfo
	u.require(userResponseFieldAccountInfo)
}

// SetUsage sets the Usage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserResponse) SetUsage(usage *UserUsage) {
	u.Usage = usage
	u.require(userResponseFieldUsage)
}

func (u *UserResponse) UnmarshalJSON(data []byte) error {
	type embed UserResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UserResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.ExtraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserResponse) MarshalJSON() ([]byte, error) {
	type embed UserResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, u.ExtraProperties)
}

func (u *UserResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	userUsageFieldRequestLimitDaily      = big.NewInt(1 << 0)
	userUsageFieldRequestsRemainingToday = big.NewInt(1 << 1)
	userUsageFieldAPIAccess              = big.NewInt(1 << 2)
)

type UserUsage struct {
	// Lookups per day on this plan (Max: unlimited, shown as a very large number).
	RequestLimitDaily *float64 `json:"request_limit_daily,omitempty" url:"request_limit_daily,omitempty"`
	// Lookups left today. Resets at 00:00 UTC.
	RequestsRemainingToday *float64 `json:"requests_remaining_today,omitempty" url:"requests_remaining_today,omitempty"`
	// Whether the plan includes API access.
	APIAccess *bool `json:"api_access,omitempty" url:"api_access,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (u *UserUsage) GetRequestLimitDaily() *float64 {
	if u == nil {
		return nil
	}
	return u.RequestLimitDaily
}

func (u *UserUsage) GetRequestsRemainingToday() *float64 {
	if u == nil {
		return nil
	}
	return u.RequestsRemainingToday
}

func (u *UserUsage) GetAPIAccess() *bool {
	if u == nil {
		return nil
	}
	return u.APIAccess
}

func (u *UserUsage) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.ExtraProperties
}

func (u *UserUsage) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetRequestLimitDaily sets the RequestLimitDaily field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserUsage) SetRequestLimitDaily(requestLimitDaily *float64) {
	u.RequestLimitDaily = requestLimitDaily
	u.require(userUsageFieldRequestLimitDaily)
}

// SetRequestsRemainingToday sets the RequestsRemainingToday field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserUsage) SetRequestsRemainingToday(requestsRemainingToday *float64) {
	u.RequestsRemainingToday = requestsRemainingToday
	u.require(userUsageFieldRequestsRemainingToday)
}

// SetAPIAccess sets the APIAccess field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserUsage) SetAPIAccess(apiAccess *bool) {
	u.APIAccess = apiAccess
	u.require(userUsageFieldAPIAccess)
}

func (u *UserUsage) UnmarshalJSON(data []byte) error {
	type embed UserUsage
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UserUsage(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.ExtraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserUsage) MarshalJSON() ([]byte, error) {
	type embed UserUsage
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, u.ExtraProperties)
}

func (u *UserUsage) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}
