// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersDatabaseSearchBreachRequest(t *testing.T) {
	t.Run("SetQuery", func(t *testing.T) {
		obj := &DatabaseSearchBreachRequest{}
		var fernTestValueQuery string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQueryType", func(t *testing.T) {
		obj := &DatabaseSearchBreachRequest{}
		var fernTestValueQueryType *DatabaseSearchBreachRequestType
		obj.SetQueryType(fernTestValueQueryType)
		assert.Equal(t, fernTestValueQueryType, obj.QueryType)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDatabaseSearchBreachRequest(t *testing.T) {
	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchBreachRequest{}
		var fernTestValueQuery string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQueryType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchBreachRequest{}
		var fernTestValueQueryType *DatabaseSearchBreachRequestType

		// Act
		obj.SetQueryType(fernTestValueQueryType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDomainBreachRequest(t *testing.T) {
	t.Run("SetQuery", func(t *testing.T) {
		obj := &DomainBreachRequest{}
		var fernTestValueQuery string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDomainBreachRequest(t *testing.T) {
	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DomainBreachRequest{}
		var fernTestValueQuery string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSearchBreachRequest(t *testing.T) {
	t.Run("SetQuery", func(t *testing.T) {
		obj := &SearchBreachRequest{}
		var fernTestValueQuery string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSearchBreachRequest(t *testing.T) {
	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SearchBreachRequest{}
		var fernTestValueQuery string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersBreachResponse(t *testing.T) {
	t.Run("SetAPI", func(t *testing.T) {
		obj := &BreachResponse{}
		var fernTestValueAPI *string
		obj.SetAPI(fernTestValueAPI)
		assert.Equal(t, fernTestValueAPI, obj.API)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetElapsedMs", func(t *testing.T) {
		obj := &BreachResponse{}
		var fernTestValueElapsedMs *float64
		obj.SetElapsedMs(fernTestValueElapsedMs)
		assert.Equal(t, fernTestValueElapsedMs, obj.ElapsedMs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimestamp", func(t *testing.T) {
		obj := &BreachResponse{}
		var fernTestValueTimestamp *string
		obj.SetTimestamp(fernTestValueTimestamp)
		assert.Equal(t, fernTestValueTimestamp, obj.Timestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResultsCount", func(t *testing.T) {
		obj := &BreachResponse{}
		var fernTestValueResultsCount *float64
		obj.SetResultsCount(fernTestValueResultsCount)
		assert.Equal(t, fernTestValueResultsCount, obj.ResultsCount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBreachData", func(t *testing.T) {
		obj := &BreachResponse{}
		var fernTestValueBreachData []any
		obj.SetBreachData(fernTestValueBreachData)
		assert.Equal(t, fernTestValueBreachData, obj.BreachData)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMeta", func(t *testing.T) {
		obj := &BreachResponse{}
		var fernTestValueMeta *UsageMeta
		obj.SetMeta(fernTestValueMeta)
		assert.Equal(t, fernTestValueMeta, obj.Meta)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersBreachResponse(t *testing.T) {
	t.Run("GetAPI", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var expected *string
		obj.API = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAPI(), "getter should return the property value")
	})

	t.Run("GetAPI_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		obj.API = nil

		// Act & Assert
		assert.Nil(t, obj.GetAPI(), "getter should return nil when property is nil")
	})

	t.Run("GetAPI_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BreachResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAPI() // Should return zero value
	})

	t.Run("GetElapsedMs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var expected *float64
		obj.ElapsedMs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetElapsedMs(), "getter should return the property value")
	})

	t.Run("GetElapsedMs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		obj.ElapsedMs = nil

		// Act & Assert
		assert.Nil(t, obj.GetElapsedMs(), "getter should return nil when property is nil")
	})

	t.Run("GetElapsedMs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BreachResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetElapsedMs() // Should return zero value
	})

	t.Run("GetTimestamp", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var expected *string
		obj.Timestamp = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimestamp(), "getter should return the property value")
	})

	t.Run("GetTimestamp_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		obj.Timestamp = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimestamp(), "getter should return nil when property is nil")
	})

	t.Run("GetTimestamp_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BreachResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimestamp() // Should return zero value
	})

	t.Run("GetResultsCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var expected *float64
		obj.ResultsCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResultsCount(), "getter should return the property value")
	})

	t.Run("GetResultsCount_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		obj.ResultsCount = nil

		// Act & Assert
		assert.Nil(t, obj.GetResultsCount(), "getter should return nil when property is nil")
	})

	t.Run("GetResultsCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BreachResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResultsCount() // Should return zero value
	})

	t.Run("GetBreachData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var expected []any
		obj.BreachData = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBreachData(), "getter should return the property value")
	})

	t.Run("GetBreachData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		obj.BreachData = nil

		// Act & Assert
		assert.Nil(t, obj.GetBreachData(), "getter should return nil when property is nil")
	})

	t.Run("GetBreachData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BreachResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBreachData() // Should return zero value
	})

	t.Run("GetMeta", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var expected *UsageMeta
		obj.Meta = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMeta(), "getter should return the property value")
	})

	t.Run("GetMeta_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		obj.Meta = nil

		// Act & Assert
		assert.Nil(t, obj.GetMeta(), "getter should return nil when property is nil")
	})

	t.Run("GetMeta_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BreachResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMeta() // Should return zero value
	})

}

func TestSettersMarkExplicitBreachResponse(t *testing.T) {
	t.Run("SetAPI_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var fernTestValueAPI *string

		// Act
		obj.SetAPI(fernTestValueAPI)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetElapsedMs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var fernTestValueElapsedMs *float64

		// Act
		obj.SetElapsedMs(fernTestValueElapsedMs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var fernTestValueTimestamp *string

		// Act
		obj.SetTimestamp(fernTestValueTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResultsCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var fernTestValueResultsCount *float64

		// Act
		obj.SetResultsCount(fernTestValueResultsCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBreachData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var fernTestValueBreachData []any

		// Act
		obj.SetBreachData(fernTestValueBreachData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMeta_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}
		var fernTestValueMeta *UsageMeta

		// Act
		obj.SetMeta(fernTestValueMeta)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDatabaseSearchResponse(t *testing.T) {
	t.Run("SetResults", func(t *testing.T) {
		obj := &DatabaseSearchResponse{}
		var fernTestValueResults []any
		obj.SetResults(fernTestValueResults)
		assert.Equal(t, fernTestValueResults, obj.Results)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResultsCount", func(t *testing.T) {
		obj := &DatabaseSearchResponse{}
		var fernTestValueResultsCount *float64
		obj.SetResultsCount(fernTestValueResultsCount)
		assert.Equal(t, fernTestValueResultsCount, obj.ResultsCount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuery", func(t *testing.T) {
		obj := &DatabaseSearchResponse{}
		var fernTestValueQuery *string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQueryType", func(t *testing.T) {
		obj := &DatabaseSearchResponse{}
		var fernTestValueQueryType *string
		obj.SetQueryType(fernTestValueQueryType)
		assert.Equal(t, fernTestValueQueryType, obj.QueryType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExecutionTime", func(t *testing.T) {
		obj := &DatabaseSearchResponse{}
		var fernTestValueExecutionTime *string
		obj.SetExecutionTime(fernTestValueExecutionTime)
		assert.Equal(t, fernTestValueExecutionTime, obj.ExecutionTime)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &DatabaseSearchResponse{}
		var fernTestValueStatus *string
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDatabaseSearchResponse(t *testing.T) {
	t.Run("GetResults", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var expected []any
		obj.Results = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResults(), "getter should return the property value")
	})

	t.Run("GetResults_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		obj.Results = nil

		// Act & Assert
		assert.Nil(t, obj.GetResults(), "getter should return nil when property is nil")
	})

	t.Run("GetResults_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSearchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResults() // Should return zero value
	})

	t.Run("GetResultsCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var expected *float64
		obj.ResultsCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResultsCount(), "getter should return the property value")
	})

	t.Run("GetResultsCount_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		obj.ResultsCount = nil

		// Act & Assert
		assert.Nil(t, obj.GetResultsCount(), "getter should return nil when property is nil")
	})

	t.Run("GetResultsCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSearchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResultsCount() // Should return zero value
	})

	t.Run("GetQuery", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var expected *string
		obj.Query = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetQuery(), "getter should return the property value")
	})

	t.Run("GetQuery_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		obj.Query = nil

		// Act & Assert
		assert.Nil(t, obj.GetQuery(), "getter should return nil when property is nil")
	})

	t.Run("GetQuery_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSearchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetQuery() // Should return zero value
	})

	t.Run("GetQueryType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var expected *string
		obj.QueryType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetQueryType(), "getter should return the property value")
	})

	t.Run("GetQueryType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		obj.QueryType = nil

		// Act & Assert
		assert.Nil(t, obj.GetQueryType(), "getter should return nil when property is nil")
	})

	t.Run("GetQueryType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSearchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetQueryType() // Should return zero value
	})

	t.Run("GetExecutionTime", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var expected *string
		obj.ExecutionTime = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExecutionTime(), "getter should return the property value")
	})

	t.Run("GetExecutionTime_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		obj.ExecutionTime = nil

		// Act & Assert
		assert.Nil(t, obj.GetExecutionTime(), "getter should return nil when property is nil")
	})

	t.Run("GetExecutionTime_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSearchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExecutionTime() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var expected *string
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		obj.Status = nil

		// Act & Assert
		assert.Nil(t, obj.GetStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSearchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

}

func TestSettersMarkExplicitDatabaseSearchResponse(t *testing.T) {
	t.Run("SetResults_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var fernTestValueResults []any

		// Act
		obj.SetResults(fernTestValueResults)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResultsCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var fernTestValueResultsCount *float64

		// Act
		obj.SetResultsCount(fernTestValueResultsCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var fernTestValueQuery *string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQueryType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var fernTestValueQueryType *string

		// Act
		obj.SetQueryType(fernTestValueQueryType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExecutionTime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var fernTestValueExecutionTime *string

		// Act
		obj.SetExecutionTime(fernTestValueExecutionTime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}
		var fernTestValueStatus *string

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingBreachResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BreachResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled BreachResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj BreachResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj BreachResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingDatabaseSearchResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSearchResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled DatabaseSearchResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj DatabaseSearchResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj DatabaseSearchResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringBreachResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &BreachResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BreachResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringDatabaseSearchResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &DatabaseSearchResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSearchResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumDatabaseSearchBreachRequestType(t *testing.T) {
	t.Run("NewFromString_email", func(t *testing.T) {
		t.Parallel()
		val, err := NewDatabaseSearchBreachRequestTypeFromString("email")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DatabaseSearchBreachRequestType("email"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_domain", func(t *testing.T) {
		t.Parallel()
		val, err := NewDatabaseSearchBreachRequestTypeFromString("domain")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DatabaseSearchBreachRequestType("domain"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewDatabaseSearchBreachRequestTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewDatabaseSearchBreachRequestTypeFromString("email")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesBreachResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &BreachResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BreachResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesDatabaseSearchResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &DatabaseSearchResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSearchResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
