// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	databaseSearchBreachRequestFieldQuery     = big.NewInt(1 << 0)
	databaseSearchBreachRequestFieldQueryType = big.NewInt(1 << 1)
)

type DatabaseSearchBreachRequest struct {
	// The e-mail address or domain.
	Query string `json:"-" url:"query"`
	// `email` or `domain`. Detected from `query` when left out.
	QueryType *DatabaseSearchBreachRequestType `json:"-" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DatabaseSearchBreachRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSearchBreachRequest) SetQuery(query string) {
	d.Query = query
	d.require(databaseSearchBreachRequestFieldQuery)
}

// SetQueryType sets the QueryType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSearchBreachRequest) SetQueryType(queryType *DatabaseSearchBreachRequestType) {
	d.QueryType = queryType
	d.require(databaseSearchBreachRequestFieldQueryType)
}

var (
	domainBreachRequestFieldQuery = big.NewInt(1 << 0)
)

type DomainBreachRequest struct {
	// The domain, e.g. `example.com`.
	Query string `json:"-" url:"query"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DomainBreachRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DomainBreachRequest) SetQuery(query string) {
	d.Query = query
	d.require(domainBreachRequestFieldQuery)
}

var (
	searchBreachRequestFieldQuery = big.NewInt(1 << 0)
)

type SearchBreachRequest struct {
	// What to search for: an e-mail address, username, domain, phone number, IP address, name or password.
	Query string `json:"-" url:"query"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchBreachRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchBreachRequest) SetQuery(query string) {
	s.Query = query
	s.require(searchBreachRequestFieldQuery)
}

var (
	breachResponseFieldAPI          = big.NewInt(1 << 0)
	breachResponseFieldElapsedMs    = big.NewInt(1 << 1)
	breachResponseFieldTimestamp    = big.NewInt(1 << 2)
	breachResponseFieldResultsCount = big.NewInt(1 << 3)
	breachResponseFieldBreachData   = big.NewInt(1 << 4)
	breachResponseFieldMeta         = big.NewInt(1 << 5)
)

type BreachResponse struct {
	// Always `OsintCat`.
	API *string `json:"api,omitempty" url:"api,omitempty"`
	// Time the search took, in milliseconds.
	ElapsedMs *float64 `json:"elapsed_ms,omitempty" url:"elapsed_ms,omitempty"`
	// When the search ran (UTC), e.g. `Oct 6th 09:41`.
	Timestamp *string `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	// Number of records in `breach_data`.
	ResultsCount *float64 `json:"results_count,omitempty" url:"results_count,omitempty"`
	// Matching records. The fields of a record depend on the breach it comes from (for example `email`, `username`, `password`, `hash`, `ip`, `name`, `phone`); `source_db` names the breach or index the record was found in.
	BreachData []any      `json:"breach_data,omitempty" url:"breach_data,omitempty"`
	Meta       *UsageMeta `json:"_meta,omitempty" url:"_meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (b *BreachResponse) GetAPI() *string {
	if b == nil {
		return nil
	}
	return b.API
}

func (b *BreachResponse) GetElapsedMs() *float64 {
	if b == nil {
		return nil
	}
	return b.ElapsedMs
}

func (b *BreachResponse) GetTimestamp() *string {
	if b == nil {
		return nil
	}
	return b.Timestamp
}

func (b *BreachResponse) GetResultsCount() *float64 {
	if b == nil {
		return nil
	}
	return b.ResultsCount
}

func (b *BreachResponse) GetBreachData() []any {
	if b == nil {
		return nil
	}
	return b.BreachData
}

func (b *BreachResponse) GetMeta() *UsageMeta {
	if b == nil {
		return nil
	}
	return b.Meta
}

func (b *BreachResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.ExtraProperties
}

func (b *BreachResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetAPI sets the API field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BreachResponse) SetAPI(api_ *string) {
	b.API = api_
	b.require(breachResponseFieldAPI)
}

// SetElapsedMs sets the ElapsedMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BreachResponse) SetElapsedMs(elapsedMs *float64) {
	b.ElapsedMs = elapsedMs
	b.require(breachResponseFieldElapsedMs)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BreachResponse) SetTimestamp(timestamp *string) {
	b.Timestamp = timestamp
	b.require(breachResponseFieldTimestamp)
}

// SetResultsCount sets the ResultsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BreachResponse) SetResultsCount(resultsCount *float64) {
	b.ResultsCount = resultsCount
	b.require(breachResponseFieldResultsCount)
}

// SetBreachData sets the BreachData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BreachResponse) SetBreachData(breachData []any) {
	b.BreachData = breachData
	b.require(breachResponseFieldBreachData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BreachResponse) SetMeta(meta *UsageMeta) {
	b.Meta = meta
	b.require(breachResponseFieldMeta)
}

func (b *BreachResponse) UnmarshalJSON(data []byte) error {
	type embed BreachResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*b = BreachResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.ExtraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BreachResponse) MarshalJSON() ([]byte, error) {
	type embed BreachResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, b.ExtraProperties)
}

func (b *BreachResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	databaseSearchResponseFieldResults       = big.NewInt(1 << 0)
	databaseSearchResponseFieldResultsCount  = big.NewInt(1 << 1)
	databaseSearchResponseFieldQuery         = big.NewInt(1 << 2)
	databaseSearchResponseFieldQueryType     = big.NewInt(1 << 3)
	databaseSearchResponseFieldExecutionTime = big.NewInt(1 << 4)
	databaseSearchResponseFieldStatus        = big.NewInt(1 << 5)
)

type DatabaseSearchResponse struct {
	// Matching entries (typically a URL, login and password, and when it was collected).
	Results []any `json:"results,omitempty" url:"results,omitempty"`
	// Number of entries.
	ResultsCount *float64 `json:"results_count,omitempty" url:"results_count,omitempty"`
	// The query searched for.
	Query *string `json:"query,omitempty" url:"query,omitempty"`
	// `email` or `domain`.
	QueryType *string `json:"type,omitempty" url:"type,omitempty"`
	// Time the search took.
	ExecutionTime *string `json:"execution_time,omitempty" url:"execution_time,omitempty"`
	// `success`.
	Status *string `json:"status,omitempty" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DatabaseSearchResponse) GetResults() []any {
	if d == nil {
		return nil
	}
	return d.Results
}

func (d *DatabaseSearchResponse) GetResultsCount() *float64 {
	if d == nil {
		return nil
	}
	return d.ResultsCount
}

func (d *DatabaseSearchResponse) GetQuery() *string {
	if d == nil {
		return nil
	}
	return d.Query
}

func (d *DatabaseSearchResponse) GetQueryType() *string {
	if d == nil {
		return nil
	}
	return d.QueryType
}

func (d *DatabaseSearchResponse) GetExecutionTime() *string {
	if d == nil {
		return nil
	}
	return d.ExecutionTime
}

func (d *DatabaseSearchResponse) GetStatus() *string {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DatabaseSearchResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DatabaseSearchResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSearchResponse) SetResults(results []any) {
	d.Results = results
	d.require(databaseSearchResponseFieldResults)
}

// SetResultsCount sets the ResultsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSearchResponse) SetResultsCount(resultsCount *float64) {
	d.ResultsCount = resultsCount
	d.require(databaseSearchResponseFieldResultsCount)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSearchResponse) SetQuery(query *string) {
	d.Query = query
	d.require(databaseSearchResponseFieldQuery)
}

// SetQueryType sets the QueryType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSearchResponse) SetQueryType(queryType *string) {
	d.QueryType = queryType
	d.require(databaseSearchResponseFieldQueryType)
}

// SetExecutionTime sets the ExecutionTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSearchResponse) SetExecutionTime(executionTime *string) {
	d.ExecutionTime = executionTime
	d.require(databaseSearchResponseFieldExecutionTime)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSearchResponse) SetStatus(status *string) {
	d.Status = status
	d.require(databaseSearchResponseFieldStatus)
}

func (d *DatabaseSearchResponse) UnmarshalJSON(data []byte) error {
	type embed DatabaseSearchResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DatabaseSearchResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DatabaseSearchResponse) MarshalJSON() ([]byte, error) {
	type embed DatabaseSearchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DatabaseSearchResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// An array of breach records. The fields of a record depend on the breach it comes from.
type DomainResponse = []map[string]any

type DatabaseSearchBreachRequestType string

const (
	DatabaseSearchBreachRequestTypeEmail  DatabaseSearchBreachRequestType = "email"
	DatabaseSearchBreachRequestTypeDomain DatabaseSearchBreachRequestType = "domain"
)

func NewDatabaseSearchBreachRequestTypeFromString(s string) (DatabaseSearchBreachRequestType, error) {
	switch s {
	case "email":
		return DatabaseSearchBreachRequestTypeEmail, nil
	case "domain":
		return DatabaseSearchBreachRequestTypeDomain, nil
	}
	var t DatabaseSearchBreachRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DatabaseSearchBreachRequestType) Ptr() *DatabaseSearchBreachRequestType {
	return &d
}
