// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	lookupChessRequestFieldQuery = big.NewInt(1 << 0)
)

type LookupChessRequest struct {
	// A Chess.com username or an e-mail address.
	Query string `json:"-" url:"query"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LookupChessRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LookupChessRequest) SetQuery(query string) {
	l.Query = query
	l.require(lookupChessRequestFieldQuery)
}

var (
	chessResponseFieldSuccess          = big.NewInt(1 << 0)
	chessResponseFieldFound            = big.NewInt(1 << 1)
	chessResponseFieldQuery            = big.NewInt(1 << 2)
	chessResponseFieldResolvedUsername = big.NewInt(1 << 3)
	chessResponseFieldLiveProfile      = big.NewInt(1 << 4)
	chessResponseFieldLiveStats        = big.NewInt(1 << 5)
	chessResponseFieldLiveClubs        = big.NewInt(1 << 6)
	chessResponseFieldLeakRecords      = big.NewInt(1 << 7)
	chessResponseFieldLeakCount        = big.NewInt(1 << 8)
)

type ChessResponse struct {
	// `true` when the lookup ran.
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Whether anything was found.
	Found *bool `json:"found,omitempty" url:"found,omitempty"`
	// The query.
	Query *string `json:"query,omitempty" url:"query,omitempty"`
	// The username the lookup settled on.
	ResolvedUsername *string `json:"resolved_username,omitempty" url:"resolved_username,omitempty"`
	// The public profile (name, country, joined, last online, followers ...), or `null`.
	LiveProfile map[string]any `json:"live_profile,omitempty" url:"live_profile,omitempty"`
	// Ratings: `rapid`, `blitz`, `bullet`, `fide` (each `null` when unrated).
	LiveStats map[string]any `json:"live_stats,omitempty" url:"live_stats,omitempty"`
	// Up to 10 clubs.
	LiveClubs []any `json:"live_clubs,omitempty" url:"live_clubs,omitempty"`
	// Records from the Chess.com leak.
	LeakRecords []any `json:"leak_records,omitempty" url:"leak_records,omitempty"`
	// Number of leak records.
	LeakCount *float64 `json:"leak_count,omitempty" url:"leak_count,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (c *ChessResponse) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

func (c *ChessResponse) GetFound() *bool {
	if c == nil {
		return nil
	}
	return c.Found
}

func (c *ChessResponse) GetQuery() *string {
	if c == nil {
		return nil
	}
	return c.Query
}

func (c *ChessResponse) GetResolvedUsername() *string {
	if c == nil {
		return nil
	}
	return c.ResolvedUsername
}

func (c *ChessResponse) GetLiveProfile() map[string]any {
	if c == nil {
		return nil
	}
	return c.LiveProfile
}

func (c *ChessResponse) GetLiveStats() map[string]any {
	if c == nil {
		return nil
	}
	return c.LiveStats
}

func (c *ChessResponse) GetLiveClubs() []any {
	if c == nil {
		return nil
	}
	return c.LiveClubs
}

func (c *ChessResponse) GetLeakRecords() []any {
	if c == nil {
		return nil
	}
	return c.LeakRecords
}

func (c *ChessResponse) GetLeakCount() *float64 {
	if c == nil {
		return nil
	}
	return c.LeakCount
}

func (c *ChessResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.ExtraProperties
}

func (c *ChessResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChessResponse) SetSuccess(success *bool) {
	c.Success = success
	c.require(chessResponseFieldSuccess)
}

// SetFound sets the Found field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChessResponse) SetFound(found *bool) {
	c.Found = found
	c.require(chessResponseFieldFound)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChessResponse) SetQuery(query *string) {
	c.Query = query
	c.require(chessResponseFieldQuery)
}

// SetResolvedUsername sets the ResolvedUsername field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChessResponse) SetResolvedUsername(resolvedUsername *string) {
	c.ResolvedUsername = resolvedUsername
	c.require(chessResponseFieldResolvedUsername)
}

// SetLiveProfile sets the LiveProfile field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChessResponse) SetLiveProfile(liveProfile map[string]any) {
	c.LiveProfile = liveProfile
	c.require(chessResponseFieldLiveProfile)
}

// SetLiveStats sets the LiveStats field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChessResponse) SetLiveStats(liveStats map[string]any) {
	c.LiveStats = liveStats
	c.require(chessResponseFieldLiveStats)
}

// SetLiveClubs sets the LiveClubs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChessResponse) SetLiveClubs(liveClubs []any) {
	c.LiveClubs = liveClubs
	c.require(chessResponseFieldLiveClubs)
}

// SetLeakRecords sets the LeakRecords field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChessResponse) SetLeakRecords(leakRecords []any) {
	c.LeakRecords = leakRecords
	c.require(chessResponseFieldLeakRecords)
}

// SetLeakCount sets the LeakCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChessResponse) SetLeakCount(leakCount *float64) {
	c.LeakCount = leakCount
	c.require(chessResponseFieldLeakCount)
}

func (c *ChessResponse) UnmarshalJSON(data []byte) error {
	type embed ChessResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ChessResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.ExtraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChessResponse) MarshalJSON() ([]byte, error) {
	type embed ChessResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, c.ExtraProperties)
}

func (c *ChessResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
