// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	big "math/big"
)

var (
	resolveDNSRequestFieldQuery = big.NewInt(1 << 0)
)

type ResolveDNSRequest struct {
	// A hostname, or several separated by commas.
	Query string `json:"-" url:"query"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ResolveDNSRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveDNSRequest) SetQuery(query string) {
	r.Query = query
	r.require(resolveDNSRequestFieldQuery)
}

// An object mapping each hostname to its IP address (`null` when it does not resolve).
type DNSResolverResponse = map[string]string
