// Code generated by Fern. DO NOT EDIT.

package osintcat

// Environments defines all of the API environments.
// These values can be used with the WithBaseURL
// RequestOption to override the client's default environment,
// if any.
var Environments = struct {
	Production string
}{
	Production: "https://www.osintcat.net",
}
