// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	core "github.com/OsintCatHQ/osintcat-go/core"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	401: func(apiError *core.APIError) error {
		return &UnauthorizedError{
			APIError: apiError,
		}
	},
	403: func(apiError *core.APIError) error {
		return &ForbiddenError{
			APIError: apiError,
		}
	},
	429: func(apiError *core.APIError) error {
		return &TooManyRequestsError{
			APIError: apiError,
		}
	},
	424: func(apiError *core.APIError) error {
		return &FailedDependencyError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
	402: func(apiError *core.APIError) error {
		return &PaymentRequiredError{
			APIError: apiError,
		}
	},
	422: func(apiError *core.APIError) error {
		return &UnprocessableEntityError{
			APIError: apiError,
		}
	},
}
