// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	profileGithubRequestFieldUsername = big.NewInt(1 << 0)
)

type ProfileGithubRequest struct {
	// The GitHub username.
	Username string `json:"-" url:"username"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProfileGithubRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProfileGithubRequest) SetUsername(username string) {
	p.Username = username
	p.require(profileGithubRequestFieldUsername)
}

var (
	githubExtraDataFieldUsername     = big.NewInt(1 << 0)
	githubExtraDataFieldName         = big.NewInt(1 << 1)
	githubExtraDataFieldBio          = big.NewInt(1 << 2)
	githubExtraDataFieldLocation     = big.NewInt(1 << 3)
	githubExtraDataFieldCompany      = big.NewInt(1 << 4)
	githubExtraDataFieldBlog         = big.NewInt(1 << 5)
	githubExtraDataFieldEmail        = big.NewInt(1 << 6)
	githubExtraDataFieldTwitter      = big.NewInt(1 << 7)
	githubExtraDataFieldFollowers    = big.NewInt(1 << 8)
	githubExtraDataFieldFollowing    = big.NewInt(1 << 9)
	githubExtraDataFieldPublicRepos  = big.NewInt(1 << 10)
	githubExtraDataFieldCreatedAt    = big.NewInt(1 << 11)
	githubExtraDataFieldProfileURL   = big.NewInt(1 << 12)
	githubExtraDataFieldRepositories = big.NewInt(1 << 13)
)

type GithubExtraData struct {
	// Login.
	Username *string `json:"Username,omitempty" url:"Username,omitempty"`
	// Name.
	Name *string `json:"Name,omitempty" url:"Name,omitempty"`
	// Bio.
	Bio *string `json:"Bio,omitempty" url:"Bio,omitempty"`
	// Location.
	Location *string `json:"Location,omitempty" url:"Location,omitempty"`
	// Company.
	Company *string `json:"Company,omitempty" url:"Company,omitempty"`
	// Website.
	Blog *string `json:"Blog,omitempty" url:"Blog,omitempty"`
	// Public e-mail.
	Email *string `json:"Email,omitempty" url:"Email,omitempty"`
	// X/Twitter handle.
	Twitter *string `json:"Twitter,omitempty" url:"Twitter,omitempty"`
	// Followers.
	Followers *float64 `json:"Followers,omitempty" url:"Followers,omitempty"`
	// Following.
	Following *float64 `json:"Following,omitempty" url:"Following,omitempty"`
	// Public repositories.
	PublicRepos *float64 `json:"PublicRepos,omitempty" url:"PublicRepos,omitempty"`
	// Account creation.
	CreatedAt *string `json:"CreatedAt,omitempty" url:"CreatedAt,omitempty"`
	// Profile link.
	ProfileURL *string `json:"ProfileUrl,omitempty" url:"ProfileUrl,omitempty"`
	// The 10 most recently pushed repositories (name, description, url, language, stars, forks).
	Repositories []any `json:"Repositories,omitempty" url:"Repositories,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (g *GithubExtraData) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

func (g *GithubExtraData) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *GithubExtraData) GetBio() *string {
	if g == nil {
		return nil
	}
	return g.Bio
}

func (g *GithubExtraData) GetLocation() *string {
	if g == nil {
		return nil
	}
	return g.Location
}

func (g *GithubExtraData) GetCompany() *string {
	if g == nil {
		return nil
	}
	return g.Company
}

func (g *GithubExtraData) GetBlog() *string {
	if g == nil {
		return nil
	}
	return g.Blog
}

func (g *GithubExtraData) GetEmail() *string {
	if g == nil {
		return nil
	}
	return g.Email
}

func (g *GithubExtraData) GetTwitter() *string {
	if g == nil {
		return nil
	}
	return g.Twitter
}

func (g *GithubExtraData) GetFollowers() *float64 {
	if g == nil {
		return nil
	}
	return g.Followers
}

func (g *GithubExtraData) GetFollowing() *float64 {
	if g == nil {
		return nil
	}
	return g.Following
}

func (g *GithubExtraData) GetPublicRepos() *float64 {
	if g == nil {
		return nil
	}
	return g.PublicRepos
}

func (g *GithubExtraData) GetCreatedAt() *string {
	if g == nil {
		return nil
	}
	return g.CreatedAt
}

func (g *GithubExtraData) GetProfileURL() *string {
	if g == nil {
		return nil
	}
	return g.ProfileURL
}

func (g *GithubExtraData) GetRepositories() []any {
	if g == nil {
		return nil
	}
	return g.Repositories
}

func (g *GithubExtraData) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.ExtraProperties
}

func (g *GithubExtraData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetUsername(username *string) {
	g.Username = username
	g.require(githubExtraDataFieldUsername)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetName(name *string) {
	g.Name = name
	g.require(githubExtraDataFieldName)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetBio(bio *string) {
	g.Bio = bio
	g.require(githubExtraDataFieldBio)
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetLocation(location *string) {
	g.Location = location
	g.require(githubExtraDataFieldLocation)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetCompany(company *string) {
	g.Company = company
	g.require(githubExtraDataFieldCompany)
}

// SetBlog sets the Blog field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetBlog(blog *string) {
	g.Blog = blog
	g.require(githubExtraDataFieldBlog)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetEmail(email *string) {
	g.Email = email
	g.require(githubExtraDataFieldEmail)
}

// SetTwitter sets the Twitter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetTwitter(twitter *string) {
	g.Twitter = twitter
	g.require(githubExtraDataFieldTwitter)
}

// SetFollowers sets the Followers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetFollowers(followers *float64) {
	g.Followers = followers
	g.require(githubExtraDataFieldFollowers)
}

// SetFollowing sets the Following field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetFollowing(following *float64) {
	g.Following = following
	g.require(githubExtraDataFieldFollowing)
}

// SetPublicRepos sets the PublicRepos field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetPublicRepos(publicRepos *float64) {
	g.PublicRepos = publicRepos
	g.require(githubExtraDataFieldPublicRepos)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetCreatedAt(createdAt *string) {
	g.CreatedAt = createdAt
	g.require(githubExtraDataFieldCreatedAt)
}

// SetProfileURL sets the ProfileURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetProfileURL(profileURL *string) {
	g.ProfileURL = profileURL
	g.require(githubExtraDataFieldProfileURL)
}

// SetRepositories sets the Repositories field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubExtraData) SetRepositories(repositories []any) {
	g.Repositories = repositories
	g.require(githubExtraDataFieldRepositories)
}

func (g *GithubExtraData) UnmarshalJSON(data []byte) error {
	type embed GithubExtraData
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GithubExtraData(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.ExtraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubExtraData) MarshalJSON() ([]byte, error) {
	type embed GithubExtraData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, g.ExtraProperties)
}

func (g *GithubExtraData) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// `taken` is `true` when the account exists. `ExtraData` holds what the profile shows publicly; a field the profile does not have is left out. When the lookup could not be completed, `taken` is `false` and `error` says why (for example `rate_limited`, try again later).
var (
	githubResponseFieldTaken     = big.NewInt(1 << 0)
	githubResponseFieldError     = big.NewInt(1 << 1)
	githubResponseFieldExtraData = big.NewInt(1 << 2)
)

type GithubResponse struct {
	// Whether an account with this username exists.
	Taken *bool `json:"taken,omitempty" url:"taken,omitempty"`
	// Present only when the lookup could not be completed.
	Error     *string          `json:"error,omitempty" url:"error,omitempty"`
	ExtraData *GithubExtraData `json:"ExtraData,omitempty" url:"ExtraData,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (g *GithubResponse) GetTaken() *bool {
	if g == nil {
		return nil
	}
	return g.Taken
}

func (g *GithubResponse) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GithubResponse) GetExtraData() *GithubExtraData {
	if g == nil {
		return nil
	}
	return g.ExtraData
}

func (g *GithubResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.ExtraProperties
}

func (g *GithubResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTaken sets the Taken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubResponse) SetTaken(taken *bool) {
	g.Taken = taken
	g.require(githubResponseFieldTaken)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubResponse) SetError(error *string) {
	g.Error = error
	g.require(githubResponseFieldError)
}

// SetExtraData sets the ExtraData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubResponse) SetExtraData(extraData *GithubExtraData) {
	g.ExtraData = extraData
	g.require(githubResponseFieldExtraData)
}

func (g *GithubResponse) UnmarshalJSON(data []byte) error {
	type embed GithubResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GithubResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.ExtraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubResponse) MarshalJSON() ([]byte, error) {
	type embed GithubResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, g.ExtraProperties)
}

func (g *GithubResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
