// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersResolveShareLinkInstagramRequest(t *testing.T) {
	t.Run("SetLink", func(t *testing.T) {
		obj := &ResolveShareLinkInstagramRequest{}
		var fernTestValueLink string
		obj.SetLink(fernTestValueLink)
		assert.Equal(t, fernTestValueLink, obj.Link)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitResolveShareLinkInstagramRequest(t *testing.T) {
	t.Run("SetLink_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResolveShareLinkInstagramRequest{}
		var fernTestValueLink string

		// Act
		obj.SetLink(fernTestValueLink)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersInstagramResolverResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &InstagramResolverResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAuthor", func(t *testing.T) {
		obj := &InstagramResolverResponse{}
		var fernTestValueAuthor map[string]any
		obj.SetAuthor(fernTestValueAuthor)
		assert.Equal(t, fernTestValueAuthor, obj.Author)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSharer", func(t *testing.T) {
		obj := &InstagramResolverResponse{}
		var fernTestValueSharer map[string]any
		obj.SetSharer(fernTestValueSharer)
		assert.Equal(t, fernTestValueSharer, obj.Sharer)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEntityID", func(t *testing.T) {
		obj := &InstagramResolverResponse{}
		var fernTestValueEntityID *string
		obj.SetEntityID(fernTestValueEntityID)
		assert.Equal(t, fernTestValueEntityID, obj.EntityID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMeta", func(t *testing.T) {
		obj := &InstagramResolverResponse{}
		var fernTestValueMeta *UsageMeta
		obj.SetMeta(fernTestValueMeta)
		assert.Equal(t, fernTestValueMeta, obj.Meta)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersInstagramResolverResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InstagramResolverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetAuthor", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var expected map[string]any
		obj.Author = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAuthor(), "getter should return the property value")
	})

	t.Run("GetAuthor_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		obj.Author = nil

		// Act & Assert
		assert.Nil(t, obj.GetAuthor(), "getter should return nil when property is nil")
	})

	t.Run("GetAuthor_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InstagramResolverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAuthor() // Should return zero value
	})

	t.Run("GetSharer", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var expected map[string]any
		obj.Sharer = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSharer(), "getter should return the property value")
	})

	t.Run("GetSharer_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		obj.Sharer = nil

		// Act & Assert
		assert.Nil(t, obj.GetSharer(), "getter should return nil when property is nil")
	})

	t.Run("GetSharer_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InstagramResolverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSharer() // Should return zero value
	})

	t.Run("GetEntityID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var expected *string
		obj.EntityID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEntityID(), "getter should return the property value")
	})

	t.Run("GetEntityID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		obj.EntityID = nil

		// Act & Assert
		assert.Nil(t, obj.GetEntityID(), "getter should return nil when property is nil")
	})

	t.Run("GetEntityID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InstagramResolverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEntityID() // Should return zero value
	})

	t.Run("GetMeta", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var expected *UsageMeta
		obj.Meta = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMeta(), "getter should return the property value")
	})

	t.Run("GetMeta_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		obj.Meta = nil

		// Act & Assert
		assert.Nil(t, obj.GetMeta(), "getter should return nil when property is nil")
	})

	t.Run("GetMeta_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InstagramResolverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMeta() // Should return zero value
	})

}

func TestSettersMarkExplicitInstagramResolverResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAuthor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var fernTestValueAuthor map[string]any

		// Act
		obj.SetAuthor(fernTestValueAuthor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSharer_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var fernTestValueSharer map[string]any

		// Act
		obj.SetSharer(fernTestValueSharer)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEntityID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var fernTestValueEntityID *string

		// Act
		obj.SetEntityID(fernTestValueEntityID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMeta_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}
		var fernTestValueMeta *UsageMeta

		// Act
		obj.SetMeta(fernTestValueMeta)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingInstagramResolverResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &InstagramResolverResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled InstagramResolverResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj InstagramResolverResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj InstagramResolverResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringInstagramResolverResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &InstagramResolverResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InstagramResolverResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesInstagramResolverResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &InstagramResolverResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *InstagramResolverResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
