// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	lookupIPRequestFieldQuery = big.NewInt(1 << 0)
)

type LookupIPRequest struct {
	// An IPv4 or IPv6 address.
	Query string `json:"-" url:"query"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LookupIPRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LookupIPRequest) SetQuery(query string) {
	l.Query = query
	l.require(lookupIPRequestFieldQuery)
}

var (
	iPResponseFieldIpleaks = big.NewInt(1 << 0)
	iPResponseFieldIpinfo  = big.NewInt(1 << 1)
)

type IPResponse struct {
	// Services seen on the address: open ports, banners, hostnames, known vulnerabilities. `{"error": "No information available for that IP."}` when nothing was seen.
	Ipleaks map[string]any `json:"ipleaks,omitempty" url:"ipleaks,omitempty"`
	// Location and network: country, region, city, coordinates, time zone, ASN and organisation.
	Ipinfo map[string]any `json:"ipinfo,omitempty" url:"ipinfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (i *IPResponse) GetIpleaks() map[string]any {
	if i == nil {
		return nil
	}
	return i.Ipleaks
}

func (i *IPResponse) GetIpinfo() map[string]any {
	if i == nil {
		return nil
	}
	return i.Ipinfo
}

func (i *IPResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.ExtraProperties
}

func (i *IPResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetIpleaks sets the Ipleaks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IPResponse) SetIpleaks(ipleaks map[string]any) {
	i.Ipleaks = ipleaks
	i.require(iPResponseFieldIpleaks)
}

// SetIpinfo sets the Ipinfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IPResponse) SetIpinfo(ipinfo map[string]any) {
	i.Ipinfo = ipinfo
	i.require(iPResponseFieldIpinfo)
}

func (i *IPResponse) UnmarshalJSON(data []byte) error {
	type embed IPResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IPResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.ExtraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IPResponse) MarshalJSON() ([]byte, error) {
	type embed IPResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, i.ExtraProperties)
}

func (i *IPResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}
