// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersLeaksMinecraftRequest(t *testing.T) {
	t.Run("SetQuery", func(t *testing.T) {
		obj := &LeaksMinecraftRequest{}
		var fernTestValueQuery string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQueryType", func(t *testing.T) {
		obj := &LeaksMinecraftRequest{}
		var fernTestValueQueryType LeaksMinecraftRequestType
		obj.SetQueryType(fernTestValueQueryType)
		assert.Equal(t, fernTestValueQueryType, obj.QueryType)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitLeaksMinecraftRequest(t *testing.T) {
	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LeaksMinecraftRequest{}
		var fernTestValueQuery string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQueryType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LeaksMinecraftRequest{}
		var fernTestValueQueryType LeaksMinecraftRequestType

		// Act
		obj.SetQueryType(fernTestValueQueryType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPlayerMinecraftRequest(t *testing.T) {
	t.Run("SetQuery", func(t *testing.T) {
		obj := &PlayerMinecraftRequest{}
		var fernTestValueQuery string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQueryType", func(t *testing.T) {
		obj := &PlayerMinecraftRequest{}
		var fernTestValueQueryType *PlayerMinecraftRequestType
		obj.SetQueryType(fernTestValueQueryType)
		assert.Equal(t, fernTestValueQueryType, obj.QueryType)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPlayerMinecraftRequest(t *testing.T) {
	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PlayerMinecraftRequest{}
		var fernTestValueQuery string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQueryType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PlayerMinecraftRequest{}
		var fernTestValueQueryType *PlayerMinecraftRequestType

		// Act
		obj.SetQueryType(fernTestValueQueryType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersProfileMinecraftRequest(t *testing.T) {
	t.Run("SetUsername", func(t *testing.T) {
		obj := &ProfileMinecraftRequest{}
		var fernTestValueUsername string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProfileMinecraftRequest(t *testing.T) {
	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProfileMinecraftRequest{}
		var fernTestValueUsername string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersMinecraftProfileExtraData(t *testing.T) {
	t.Run("SetUsername", func(t *testing.T) {
		obj := &MinecraftProfileExtraData{}
		var fernTestValueUsername *string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUUID", func(t *testing.T) {
		obj := &MinecraftProfileExtraData{}
		var fernTestValueUUID *string
		obj.SetUUID(fernTestValueUUID)
		assert.Equal(t, fernTestValueUUID, obj.UUID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNameHistory", func(t *testing.T) {
		obj := &MinecraftProfileExtraData{}
		var fernTestValueNameHistory []any
		obj.SetNameHistory(fernTestValueNameHistory)
		assert.Equal(t, fernTestValueNameHistory, obj.NameHistory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLabyUsername", func(t *testing.T) {
		obj := &MinecraftProfileExtraData{}
		var fernTestValueLabyUsername *string
		obj.SetLabyUsername(fernTestValueLabyUsername)
		assert.Equal(t, fernTestValueLabyUsername, obj.LabyUsername)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProfilePicURL", func(t *testing.T) {
		obj := &MinecraftProfileExtraData{}
		var fernTestValueProfilePicURL *string
		obj.SetProfilePicURL(fernTestValueProfilePicURL)
		assert.Equal(t, fernTestValueProfilePicURL, obj.ProfilePicURL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersMinecraftProfileExtraData(t *testing.T) {
	t.Run("GetUsername", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var expected *string
		obj.Username = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsername(), "getter should return the property value")
	})

	t.Run("GetUsername_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		obj.Username = nil

		// Act & Assert
		assert.Nil(t, obj.GetUsername(), "getter should return nil when property is nil")
	})

	t.Run("GetUsername_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsername() // Should return zero value
	})

	t.Run("GetUUID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var expected *string
		obj.UUID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUUID(), "getter should return the property value")
	})

	t.Run("GetUUID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		obj.UUID = nil

		// Act & Assert
		assert.Nil(t, obj.GetUUID(), "getter should return nil when property is nil")
	})

	t.Run("GetUUID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUUID() // Should return zero value
	})

	t.Run("GetNameHistory", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var expected []any
		obj.NameHistory = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNameHistory(), "getter should return the property value")
	})

	t.Run("GetNameHistory_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		obj.NameHistory = nil

		// Act & Assert
		assert.Nil(t, obj.GetNameHistory(), "getter should return nil when property is nil")
	})

	t.Run("GetNameHistory_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNameHistory() // Should return zero value
	})

	t.Run("GetLabyUsername", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var expected *string
		obj.LabyUsername = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLabyUsername(), "getter should return the property value")
	})

	t.Run("GetLabyUsername_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		obj.LabyUsername = nil

		// Act & Assert
		assert.Nil(t, obj.GetLabyUsername(), "getter should return nil when property is nil")
	})

	t.Run("GetLabyUsername_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLabyUsername() // Should return zero value
	})

	t.Run("GetProfilePicURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var expected *string
		obj.ProfilePicURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProfilePicURL(), "getter should return the property value")
	})

	t.Run("GetProfilePicURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		obj.ProfilePicURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetProfilePicURL(), "getter should return nil when property is nil")
	})

	t.Run("GetProfilePicURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProfilePicURL() // Should return zero value
	})

}

func TestSettersMarkExplicitMinecraftProfileExtraData(t *testing.T) {
	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var fernTestValueUsername *string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUUID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var fernTestValueUUID *string

		// Act
		obj.SetUUID(fernTestValueUUID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNameHistory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var fernTestValueNameHistory []any

		// Act
		obj.SetNameHistory(fernTestValueNameHistory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLabyUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var fernTestValueLabyUsername *string

		// Act
		obj.SetLabyUsername(fernTestValueLabyUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProfilePicURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}
		var fernTestValueProfilePicURL *string

		// Act
		obj.SetProfilePicURL(fernTestValueProfilePicURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersMinecraftProfileResponse(t *testing.T) {
	t.Run("SetTaken", func(t *testing.T) {
		obj := &MinecraftProfileResponse{}
		var fernTestValueTaken *bool
		obj.SetTaken(fernTestValueTaken)
		assert.Equal(t, fernTestValueTaken, obj.Taken)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetError", func(t *testing.T) {
		obj := &MinecraftProfileResponse{}
		var fernTestValueError *string
		obj.SetError(fernTestValueError)
		assert.Equal(t, fernTestValueError, obj.Error)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExtraData", func(t *testing.T) {
		obj := &MinecraftProfileResponse{}
		var fernTestValueExtraData *MinecraftProfileExtraData
		obj.SetExtraData(fernTestValueExtraData)
		assert.Equal(t, fernTestValueExtraData, obj.ExtraData)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersMinecraftProfileResponse(t *testing.T) {
	t.Run("GetTaken", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}
		var expected *bool
		obj.Taken = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTaken(), "getter should return the property value")
	})

	t.Run("GetTaken_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}
		obj.Taken = nil

		// Act & Assert
		assert.Nil(t, obj.GetTaken(), "getter should return nil when property is nil")
	})

	t.Run("GetTaken_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTaken() // Should return zero value
	})

	t.Run("GetError", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}
		var expected *string
		obj.Error = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetError(), "getter should return the property value")
	})

	t.Run("GetError_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}
		obj.Error = nil

		// Act & Assert
		assert.Nil(t, obj.GetError(), "getter should return nil when property is nil")
	})

	t.Run("GetError_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetError() // Should return zero value
	})

	t.Run("GetExtraData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}
		var expected *MinecraftProfileExtraData
		obj.ExtraData = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExtraData(), "getter should return the property value")
	})

	t.Run("GetExtraData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}
		obj.ExtraData = nil

		// Act & Assert
		assert.Nil(t, obj.GetExtraData(), "getter should return nil when property is nil")
	})

	t.Run("GetExtraData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExtraData() // Should return zero value
	})

}

func TestSettersMarkExplicitMinecraftProfileResponse(t *testing.T) {
	t.Run("SetTaken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}
		var fernTestValueTaken *bool

		// Act
		obj.SetTaken(fernTestValueTaken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetError_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}
		var fernTestValueError *string

		// Act
		obj.SetError(fernTestValueError)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExtraData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}
		var fernTestValueExtraData *MinecraftProfileExtraData

		// Act
		obj.SetExtraData(fernTestValueExtraData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersMinecraftResponse(t *testing.T) {
	t.Run("SetQuery", func(t *testing.T) {
		obj := &MinecraftResponse{}
		var fernTestValueQuery *string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUUID", func(t *testing.T) {
		obj := &MinecraftResponse{}
		var fernTestValueUUID *string
		obj.SetUUID(fernTestValueUUID)
		assert.Equal(t, fernTestValueUUID, obj.UUID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUsername", func(t *testing.T) {
		obj := &MinecraftResponse{}
		var fernTestValueUsername *string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNameHistory", func(t *testing.T) {
		obj := &MinecraftResponse{}
		var fernTestValueNameHistory []any
		obj.SetNameHistory(fernTestValueNameHistory)
		assert.Equal(t, fernTestValueNameHistory, obj.NameHistory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCapes", func(t *testing.T) {
		obj := &MinecraftResponse{}
		var fernTestValueCapes []any
		obj.SetCapes(fernTestValueCapes)
		assert.Equal(t, fernTestValueCapes, obj.Capes)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSkinHistory", func(t *testing.T) {
		obj := &MinecraftResponse{}
		var fernTestValueSkinHistory []any
		obj.SetSkinHistory(fernTestValueSkinHistory)
		assert.Equal(t, fernTestValueSkinHistory, obj.SkinHistory)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResults", func(t *testing.T) {
		obj := &MinecraftResponse{}
		var fernTestValueResults any
		obj.SetResults(fernTestValueResults)
		assert.Equal(t, fernTestValueResults, obj.Results)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersMinecraftResponse(t *testing.T) {
	t.Run("GetQuery", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var expected *string
		obj.Query = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetQuery(), "getter should return the property value")
	})

	t.Run("GetQuery_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		obj.Query = nil

		// Act & Assert
		assert.Nil(t, obj.GetQuery(), "getter should return nil when property is nil")
	})

	t.Run("GetQuery_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetQuery() // Should return zero value
	})

	t.Run("GetUUID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var expected *string
		obj.UUID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUUID(), "getter should return the property value")
	})

	t.Run("GetUUID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		obj.UUID = nil

		// Act & Assert
		assert.Nil(t, obj.GetUUID(), "getter should return nil when property is nil")
	})

	t.Run("GetUUID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUUID() // Should return zero value
	})

	t.Run("GetUsername", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var expected *string
		obj.Username = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsername(), "getter should return the property value")
	})

	t.Run("GetUsername_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		obj.Username = nil

		// Act & Assert
		assert.Nil(t, obj.GetUsername(), "getter should return nil when property is nil")
	})

	t.Run("GetUsername_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsername() // Should return zero value
	})

	t.Run("GetNameHistory", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var expected []any
		obj.NameHistory = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNameHistory(), "getter should return the property value")
	})

	t.Run("GetNameHistory_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		obj.NameHistory = nil

		// Act & Assert
		assert.Nil(t, obj.GetNameHistory(), "getter should return nil when property is nil")
	})

	t.Run("GetNameHistory_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNameHistory() // Should return zero value
	})

	t.Run("GetCapes", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var expected []any
		obj.Capes = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCapes(), "getter should return the property value")
	})

	t.Run("GetCapes_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		obj.Capes = nil

		// Act & Assert
		assert.Nil(t, obj.GetCapes(), "getter should return nil when property is nil")
	})

	t.Run("GetCapes_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCapes() // Should return zero value
	})

	t.Run("GetSkinHistory", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var expected []any
		obj.SkinHistory = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSkinHistory(), "getter should return the property value")
	})

	t.Run("GetSkinHistory_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		obj.SkinHistory = nil

		// Act & Assert
		assert.Nil(t, obj.GetSkinHistory(), "getter should return nil when property is nil")
	})

	t.Run("GetSkinHistory_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSkinHistory() // Should return zero value
	})

	t.Run("GetResults", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var expected any
		obj.Results = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResults(), "getter should return the property value")
	})

	t.Run("GetResults_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResults() // Should return zero value
	})

}

func TestSettersMarkExplicitMinecraftResponse(t *testing.T) {
	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var fernTestValueQuery *string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUUID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var fernTestValueUUID *string

		// Act
		obj.SetUUID(fernTestValueUUID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var fernTestValueUsername *string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNameHistory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var fernTestValueNameHistory []any

		// Act
		obj.SetNameHistory(fernTestValueNameHistory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCapes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var fernTestValueCapes []any

		// Act
		obj.SetCapes(fernTestValueCapes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSkinHistory_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var fernTestValueSkinHistory []any

		// Act
		obj.SetSkinHistory(fernTestValueSkinHistory)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResults_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}
		var fernTestValueResults any

		// Act
		obj.SetResults(fernTestValueResults)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingMinecraftProfileExtraData(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileExtraData{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled MinecraftProfileExtraData
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj MinecraftProfileExtraData
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj MinecraftProfileExtraData
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingMinecraftProfileResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftProfileResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled MinecraftProfileResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj MinecraftProfileResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj MinecraftProfileResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingMinecraftResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MinecraftResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled MinecraftResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj MinecraftResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj MinecraftResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringMinecraftProfileExtraData(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &MinecraftProfileExtraData{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileExtraData
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringMinecraftProfileResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &MinecraftProfileResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringMinecraftResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &MinecraftResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumLeaksMinecraftRequestType(t *testing.T) {
	t.Run("NewFromString_username", func(t *testing.T) {
		t.Parallel()
		val, err := NewLeaksMinecraftRequestTypeFromString("username")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, LeaksMinecraftRequestType("username"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_uuid", func(t *testing.T) {
		t.Parallel()
		val, err := NewLeaksMinecraftRequestTypeFromString("uuid")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, LeaksMinecraftRequestType("uuid"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_email", func(t *testing.T) {
		t.Parallel()
		val, err := NewLeaksMinecraftRequestTypeFromString("email")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, LeaksMinecraftRequestType("email"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ip", func(t *testing.T) {
		t.Parallel()
		val, err := NewLeaksMinecraftRequestTypeFromString("ip")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, LeaksMinecraftRequestType("ip"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_password", func(t *testing.T) {
		t.Parallel()
		val, err := NewLeaksMinecraftRequestTypeFromString("password")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, LeaksMinecraftRequestType("password"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewLeaksMinecraftRequestTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewLeaksMinecraftRequestTypeFromString("username")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumPlayerMinecraftRequestType(t *testing.T) {
	t.Run("NewFromString_username", func(t *testing.T) {
		t.Parallel()
		val, err := NewPlayerMinecraftRequestTypeFromString("username")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, PlayerMinecraftRequestType("username"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_uuid", func(t *testing.T) {
		t.Parallel()
		val, err := NewPlayerMinecraftRequestTypeFromString("uuid")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, PlayerMinecraftRequestType("uuid"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_email", func(t *testing.T) {
		t.Parallel()
		val, err := NewPlayerMinecraftRequestTypeFromString("email")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, PlayerMinecraftRequestType("email"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ip", func(t *testing.T) {
		t.Parallel()
		val, err := NewPlayerMinecraftRequestTypeFromString("ip")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, PlayerMinecraftRequestType("ip"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewPlayerMinecraftRequestTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewPlayerMinecraftRequestTypeFromString("username")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesMinecraftProfileExtraData(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &MinecraftProfileExtraData{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileExtraData
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesMinecraftProfileResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &MinecraftProfileResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftProfileResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesMinecraftResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &MinecraftResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MinecraftResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
