// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	lookupPhoneRequestFieldQuery = big.NewInt(1 << 0)
)

type LookupPhoneRequest struct {
	// The phone number in international format, e.g. `+4915112345678`. Spaces and dashes are allowed.
	Query string `json:"-" url:"query"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LookupPhoneRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LookupPhoneRequest) SetQuery(query string) {
	l.Query = query
	l.require(lookupPhoneRequestFieldQuery)
}

var (
	phoneOsintResponseFieldModule   = big.NewInt(1 << 0)
	phoneOsintResponseFieldQuery    = big.NewInt(1 << 1)
	phoneOsintResponseFieldFound    = big.NewInt(1 << 2)
	phoneOsintResponseFieldRisk     = big.NewInt(1 << 3)
	phoneOsintResponseFieldSummary  = big.NewInt(1 << 4)
	phoneOsintResponseFieldSections = big.NewInt(1 << 5)
	phoneOsintResponseFieldRaw      = big.NewInt(1 << 6)
	phoneOsintResponseFieldMeta     = big.NewInt(1 << 7)
)

type PhoneOsintResponse struct {
	// Always `phone`.
	Module *string `json:"module,omitempty" url:"module,omitempty"`
	// The number in E.164 format.
	Query *string `json:"query,omitempty" url:"query,omitempty"`
	// Whether anything was found.
	Found *bool           `json:"found,omitempty" url:"found,omitempty"`
	Risk  *PhoneOsintRisk `json:"risk,omitempty" url:"risk,omitempty"`
	// The main facts as `{label, value}` pairs.
	Summary []any `json:"summary,omitempty" url:"summary,omitempty"`
	// Detailed findings, grouped (carrier, location, linked accounts ...).
	Sections []any `json:"sections,omitempty" url:"sections,omitempty"`
	// The full answer the summary is built from.
	Raw  map[string]any `json:"raw,omitempty" url:"raw,omitempty"`
	Meta *UsageMeta     `json:"_meta,omitempty" url:"_meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (p *PhoneOsintResponse) GetModule() *string {
	if p == nil {
		return nil
	}
	return p.Module
}

func (p *PhoneOsintResponse) GetQuery() *string {
	if p == nil {
		return nil
	}
	return p.Query
}

func (p *PhoneOsintResponse) GetFound() *bool {
	if p == nil {
		return nil
	}
	return p.Found
}

func (p *PhoneOsintResponse) GetRisk() *PhoneOsintRisk {
	if p == nil {
		return nil
	}
	return p.Risk
}

func (p *PhoneOsintResponse) GetSummary() []any {
	if p == nil {
		return nil
	}
	return p.Summary
}

func (p *PhoneOsintResponse) GetSections() []any {
	if p == nil {
		return nil
	}
	return p.Sections
}

func (p *PhoneOsintResponse) GetRaw() map[string]any {
	if p == nil {
		return nil
	}
	return p.Raw
}

func (p *PhoneOsintResponse) GetMeta() *UsageMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PhoneOsintResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.ExtraProperties
}

func (p *PhoneOsintResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetModule sets the Module field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintResponse) SetModule(module *string) {
	p.Module = module
	p.require(phoneOsintResponseFieldModule)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintResponse) SetQuery(query *string) {
	p.Query = query
	p.require(phoneOsintResponseFieldQuery)
}

// SetFound sets the Found field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintResponse) SetFound(found *bool) {
	p.Found = found
	p.require(phoneOsintResponseFieldFound)
}

// SetRisk sets the Risk field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintResponse) SetRisk(risk *PhoneOsintRisk) {
	p.Risk = risk
	p.require(phoneOsintResponseFieldRisk)
}

// SetSummary sets the Summary field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintResponse) SetSummary(summary []any) {
	p.Summary = summary
	p.require(phoneOsintResponseFieldSummary)
}

// SetSections sets the Sections field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintResponse) SetSections(sections []any) {
	p.Sections = sections
	p.require(phoneOsintResponseFieldSections)
}

// SetRaw sets the Raw field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintResponse) SetRaw(raw map[string]any) {
	p.Raw = raw
	p.require(phoneOsintResponseFieldRaw)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintResponse) SetMeta(meta *UsageMeta) {
	p.Meta = meta
	p.require(phoneOsintResponseFieldMeta)
}

func (p *PhoneOsintResponse) UnmarshalJSON(data []byte) error {
	type embed PhoneOsintResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PhoneOsintResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.ExtraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneOsintResponse) MarshalJSON() ([]byte, error) {
	type embed PhoneOsintResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, p.ExtraProperties)
}

func (p *PhoneOsintResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	phoneOsintRiskFieldScore = big.NewInt(1 << 0)
	phoneOsintRiskFieldLevel = big.NewInt(1 << 1)
)

type PhoneOsintRisk struct {
	// Score from 0 to 100, or `null`.
	Score *float64 `json:"score,omitempty" url:"score,omitempty"`
	// `low`, `medium`, `high` or `unknown`.
	Level *string `json:"level,omitempty" url:"level,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (p *PhoneOsintRisk) GetScore() *float64 {
	if p == nil {
		return nil
	}
	return p.Score
}

func (p *PhoneOsintRisk) GetLevel() *string {
	if p == nil {
		return nil
	}
	return p.Level
}

func (p *PhoneOsintRisk) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.ExtraProperties
}

func (p *PhoneOsintRisk) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetScore sets the Score field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintRisk) SetScore(score *float64) {
	p.Score = score
	p.require(phoneOsintRiskFieldScore)
}

// SetLevel sets the Level field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhoneOsintRisk) SetLevel(level *string) {
	p.Level = level
	p.require(phoneOsintRiskFieldLevel)
}

func (p *PhoneOsintRisk) UnmarshalJSON(data []byte) error {
	type embed PhoneOsintRisk
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PhoneOsintRisk(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.ExtraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhoneOsintRisk) MarshalJSON() ([]byte, error) {
	type embed PhoneOsintRisk
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, p.ExtraProperties)
}

func (p *PhoneOsintRisk) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
