// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersLookupPhoneRequest(t *testing.T) {
	t.Run("SetQuery", func(t *testing.T) {
		obj := &LookupPhoneRequest{}
		var fernTestValueQuery string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitLookupPhoneRequest(t *testing.T) {
	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LookupPhoneRequest{}
		var fernTestValueQuery string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPhoneOsintResponse(t *testing.T) {
	t.Run("SetModule", func(t *testing.T) {
		obj := &PhoneOsintResponse{}
		var fernTestValueModule *string
		obj.SetModule(fernTestValueModule)
		assert.Equal(t, fernTestValueModule, obj.Module)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuery", func(t *testing.T) {
		obj := &PhoneOsintResponse{}
		var fernTestValueQuery *string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFound", func(t *testing.T) {
		obj := &PhoneOsintResponse{}
		var fernTestValueFound *bool
		obj.SetFound(fernTestValueFound)
		assert.Equal(t, fernTestValueFound, obj.Found)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRisk", func(t *testing.T) {
		obj := &PhoneOsintResponse{}
		var fernTestValueRisk *PhoneOsintRisk
		obj.SetRisk(fernTestValueRisk)
		assert.Equal(t, fernTestValueRisk, obj.Risk)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSummary", func(t *testing.T) {
		obj := &PhoneOsintResponse{}
		var fernTestValueSummary []any
		obj.SetSummary(fernTestValueSummary)
		assert.Equal(t, fernTestValueSummary, obj.Summary)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSections", func(t *testing.T) {
		obj := &PhoneOsintResponse{}
		var fernTestValueSections []any
		obj.SetSections(fernTestValueSections)
		assert.Equal(t, fernTestValueSections, obj.Sections)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRaw", func(t *testing.T) {
		obj := &PhoneOsintResponse{}
		var fernTestValueRaw map[string]any
		obj.SetRaw(fernTestValueRaw)
		assert.Equal(t, fernTestValueRaw, obj.Raw)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMeta", func(t *testing.T) {
		obj := &PhoneOsintResponse{}
		var fernTestValueMeta *UsageMeta
		obj.SetMeta(fernTestValueMeta)
		assert.Equal(t, fernTestValueMeta, obj.Meta)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPhoneOsintResponse(t *testing.T) {
	t.Run("GetModule", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var expected *string
		obj.Module = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetModule(), "getter should return the property value")
	})

	t.Run("GetModule_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		obj.Module = nil

		// Act & Assert
		assert.Nil(t, obj.GetModule(), "getter should return nil when property is nil")
	})

	t.Run("GetModule_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetModule() // Should return zero value
	})

	t.Run("GetQuery", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var expected *string
		obj.Query = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetQuery(), "getter should return the property value")
	})

	t.Run("GetQuery_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		obj.Query = nil

		// Act & Assert
		assert.Nil(t, obj.GetQuery(), "getter should return nil when property is nil")
	})

	t.Run("GetQuery_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetQuery() // Should return zero value
	})

	t.Run("GetFound", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var expected *bool
		obj.Found = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFound(), "getter should return the property value")
	})

	t.Run("GetFound_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		obj.Found = nil

		// Act & Assert
		assert.Nil(t, obj.GetFound(), "getter should return nil when property is nil")
	})

	t.Run("GetFound_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFound() // Should return zero value
	})

	t.Run("GetRisk", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var expected *PhoneOsintRisk
		obj.Risk = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRisk(), "getter should return the property value")
	})

	t.Run("GetRisk_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		obj.Risk = nil

		// Act & Assert
		assert.Nil(t, obj.GetRisk(), "getter should return nil when property is nil")
	})

	t.Run("GetRisk_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRisk() // Should return zero value
	})

	t.Run("GetSummary", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var expected []any
		obj.Summary = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSummary(), "getter should return the property value")
	})

	t.Run("GetSummary_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		obj.Summary = nil

		// Act & Assert
		assert.Nil(t, obj.GetSummary(), "getter should return nil when property is nil")
	})

	t.Run("GetSummary_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSummary() // Should return zero value
	})

	t.Run("GetSections", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var expected []any
		obj.Sections = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSections(), "getter should return the property value")
	})

	t.Run("GetSections_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		obj.Sections = nil

		// Act & Assert
		assert.Nil(t, obj.GetSections(), "getter should return nil when property is nil")
	})

	t.Run("GetSections_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSections() // Should return zero value
	})

	t.Run("GetRaw", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var expected map[string]any
		obj.Raw = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRaw(), "getter should return the property value")
	})

	t.Run("GetRaw_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		obj.Raw = nil

		// Act & Assert
		assert.Nil(t, obj.GetRaw(), "getter should return nil when property is nil")
	})

	t.Run("GetRaw_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRaw() // Should return zero value
	})

	t.Run("GetMeta", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var expected *UsageMeta
		obj.Meta = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMeta(), "getter should return the property value")
	})

	t.Run("GetMeta_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		obj.Meta = nil

		// Act & Assert
		assert.Nil(t, obj.GetMeta(), "getter should return nil when property is nil")
	})

	t.Run("GetMeta_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMeta() // Should return zero value
	})

}

func TestSettersMarkExplicitPhoneOsintResponse(t *testing.T) {
	t.Run("SetModule_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var fernTestValueModule *string

		// Act
		obj.SetModule(fernTestValueModule)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var fernTestValueQuery *string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFound_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var fernTestValueFound *bool

		// Act
		obj.SetFound(fernTestValueFound)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRisk_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var fernTestValueRisk *PhoneOsintRisk

		// Act
		obj.SetRisk(fernTestValueRisk)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSummary_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var fernTestValueSummary []any

		// Act
		obj.SetSummary(fernTestValueSummary)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSections_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var fernTestValueSections []any

		// Act
		obj.SetSections(fernTestValueSections)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRaw_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var fernTestValueRaw map[string]any

		// Act
		obj.SetRaw(fernTestValueRaw)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMeta_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}
		var fernTestValueMeta *UsageMeta

		// Act
		obj.SetMeta(fernTestValueMeta)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPhoneOsintRisk(t *testing.T) {
	t.Run("SetScore", func(t *testing.T) {
		obj := &PhoneOsintRisk{}
		var fernTestValueScore *float64
		obj.SetScore(fernTestValueScore)
		assert.Equal(t, fernTestValueScore, obj.Score)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLevel", func(t *testing.T) {
		obj := &PhoneOsintRisk{}
		var fernTestValueLevel *string
		obj.SetLevel(fernTestValueLevel)
		assert.Equal(t, fernTestValueLevel, obj.Level)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPhoneOsintRisk(t *testing.T) {
	t.Run("GetScore", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintRisk{}
		var expected *float64
		obj.Score = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetScore(), "getter should return the property value")
	})

	t.Run("GetScore_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintRisk{}
		obj.Score = nil

		// Act & Assert
		assert.Nil(t, obj.GetScore(), "getter should return nil when property is nil")
	})

	t.Run("GetScore_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintRisk
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetScore() // Should return zero value
	})

	t.Run("GetLevel", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintRisk{}
		var expected *string
		obj.Level = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLevel(), "getter should return the property value")
	})

	t.Run("GetLevel_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintRisk{}
		obj.Level = nil

		// Act & Assert
		assert.Nil(t, obj.GetLevel(), "getter should return nil when property is nil")
	})

	t.Run("GetLevel_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintRisk
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLevel() // Should return zero value
	})

}

func TestSettersMarkExplicitPhoneOsintRisk(t *testing.T) {
	t.Run("SetScore_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintRisk{}
		var fernTestValueScore *float64

		// Act
		obj.SetScore(fernTestValueScore)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLevel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintRisk{}
		var fernTestValueLevel *string

		// Act
		obj.SetLevel(fernTestValueLevel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingPhoneOsintResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PhoneOsintResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PhoneOsintResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PhoneOsintResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingPhoneOsintRisk(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PhoneOsintRisk{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PhoneOsintRisk
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PhoneOsintRisk
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PhoneOsintRisk
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringPhoneOsintResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PhoneOsintResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringPhoneOsintRisk(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PhoneOsintRisk{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintRisk
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesPhoneOsintResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PhoneOsintResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesPhoneOsintRisk(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PhoneOsintRisk{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PhoneOsintRisk
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
