// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	profileRedditRequestFieldUsername = big.NewInt(1 << 0)
)

type ProfileRedditRequest struct {
	// The Reddit username.
	Username string `json:"-" url:"username"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProfileRedditRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProfileRedditRequest) SetUsername(username string) {
	p.Username = username
	p.require(profileRedditRequestFieldUsername)
}

var (
	redditExtraDataFieldUsername     = big.NewInt(1 << 0)
	redditExtraDataFieldDisplayName  = big.NewInt(1 << 1)
	redditExtraDataFieldCommentKarma = big.NewInt(1 << 2)
	redditExtraDataFieldLinkKarma    = big.NewInt(1 << 3)
	redditExtraDataFieldTotalKarma   = big.NewInt(1 << 4)
	redditExtraDataFieldCreatedAt    = big.NewInt(1 << 5)
	redditExtraDataFieldIsVerified   = big.NewInt(1 << 6)
	redditExtraDataFieldIsMod        = big.NewInt(1 << 7)
	redditExtraDataFieldIsSuspended  = big.NewInt(1 << 8)
	redditExtraDataFieldProfileURL   = big.NewInt(1 << 9)
)

type RedditExtraData struct {
	// Username.
	Username *string `json:"Username,omitempty" url:"Username,omitempty"`
	// Display name.
	DisplayName *string `json:"DisplayName,omitempty" url:"DisplayName,omitempty"`
	// Comment karma.
	CommentKarma *float64 `json:"CommentKarma,omitempty" url:"CommentKarma,omitempty"`
	// Post karma.
	LinkKarma *float64 `json:"LinkKarma,omitempty" url:"LinkKarma,omitempty"`
	// Total karma.
	TotalKarma *float64 `json:"TotalKarma,omitempty" url:"TotalKarma,omitempty"`
	// Account creation (Unix time).
	CreatedAt *float64 `json:"CreatedAt,omitempty" url:"CreatedAt,omitempty"`
	// Verified e-mail.
	IsVerified *bool `json:"IsVerified,omitempty" url:"IsVerified,omitempty"`
	// Moderates a community.
	IsMod *bool `json:"IsMod,omitempty" url:"IsMod,omitempty"`
	// Present and `true` for suspended accounts.
	IsSuspended *bool `json:"IsSuspended,omitempty" url:"IsSuspended,omitempty"`
	// Profile link.
	ProfileURL *string `json:"ProfileUrl,omitempty" url:"ProfileUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (r *RedditExtraData) GetUsername() *string {
	if r == nil {
		return nil
	}
	return r.Username
}

func (r *RedditExtraData) GetDisplayName() *string {
	if r == nil {
		return nil
	}
	return r.DisplayName
}

func (r *RedditExtraData) GetCommentKarma() *float64 {
	if r == nil {
		return nil
	}
	return r.CommentKarma
}

func (r *RedditExtraData) GetLinkKarma() *float64 {
	if r == nil {
		return nil
	}
	return r.LinkKarma
}

func (r *RedditExtraData) GetTotalKarma() *float64 {
	if r == nil {
		return nil
	}
	return r.TotalKarma
}

func (r *RedditExtraData) GetCreatedAt() *float64 {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *RedditExtraData) GetIsVerified() *bool {
	if r == nil {
		return nil
	}
	return r.IsVerified
}

func (r *RedditExtraData) GetIsMod() *bool {
	if r == nil {
		return nil
	}
	return r.IsMod
}

func (r *RedditExtraData) GetIsSuspended() *bool {
	if r == nil {
		return nil
	}
	return r.IsSuspended
}

func (r *RedditExtraData) GetProfileURL() *string {
	if r == nil {
		return nil
	}
	return r.ProfileURL
}

func (r *RedditExtraData) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.ExtraProperties
}

func (r *RedditExtraData) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetUsername(username *string) {
	r.Username = username
	r.require(redditExtraDataFieldUsername)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetDisplayName(displayName *string) {
	r.DisplayName = displayName
	r.require(redditExtraDataFieldDisplayName)
}

// SetCommentKarma sets the CommentKarma field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetCommentKarma(commentKarma *float64) {
	r.CommentKarma = commentKarma
	r.require(redditExtraDataFieldCommentKarma)
}

// SetLinkKarma sets the LinkKarma field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetLinkKarma(linkKarma *float64) {
	r.LinkKarma = linkKarma
	r.require(redditExtraDataFieldLinkKarma)
}

// SetTotalKarma sets the TotalKarma field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetTotalKarma(totalKarma *float64) {
	r.TotalKarma = totalKarma
	r.require(redditExtraDataFieldTotalKarma)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetCreatedAt(createdAt *float64) {
	r.CreatedAt = createdAt
	r.require(redditExtraDataFieldCreatedAt)
}

// SetIsVerified sets the IsVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetIsVerified(isVerified *bool) {
	r.IsVerified = isVerified
	r.require(redditExtraDataFieldIsVerified)
}

// SetIsMod sets the IsMod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetIsMod(isMod *bool) {
	r.IsMod = isMod
	r.require(redditExtraDataFieldIsMod)
}

// SetIsSuspended sets the IsSuspended field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetIsSuspended(isSuspended *bool) {
	r.IsSuspended = isSuspended
	r.require(redditExtraDataFieldIsSuspended)
}

// SetProfileURL sets the ProfileURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditExtraData) SetProfileURL(profileURL *string) {
	r.ProfileURL = profileURL
	r.require(redditExtraDataFieldProfileURL)
}

func (r *RedditExtraData) UnmarshalJSON(data []byte) error {
	type embed RedditExtraData
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RedditExtraData(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.ExtraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RedditExtraData) MarshalJSON() ([]byte, error) {
	type embed RedditExtraData
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, r.ExtraProperties)
}

func (r *RedditExtraData) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// `taken` is `true` when the account exists. `ExtraData` holds what the profile shows publicly; a field the profile does not have is left out. When the lookup could not be completed, `taken` is `false` and `error` says why (for example `rate_limited`, try again later).
var (
	redditResponseFieldTaken     = big.NewInt(1 << 0)
	redditResponseFieldError     = big.NewInt(1 << 1)
	redditResponseFieldExtraData = big.NewInt(1 << 2)
)

type RedditResponse struct {
	// Whether an account with this username exists.
	Taken *bool `json:"taken,omitempty" url:"taken,omitempty"`
	// Present only when the lookup could not be completed.
	Error     *string          `json:"error,omitempty" url:"error,omitempty"`
	ExtraData *RedditExtraData `json:"ExtraData,omitempty" url:"ExtraData,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (r *RedditResponse) GetTaken() *bool {
	if r == nil {
		return nil
	}
	return r.Taken
}

func (r *RedditResponse) GetError() *string {
	if r == nil {
		return nil
	}
	return r.Error
}

func (r *RedditResponse) GetExtraData() *RedditExtraData {
	if r == nil {
		return nil
	}
	return r.ExtraData
}

func (r *RedditResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.ExtraProperties
}

func (r *RedditResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetTaken sets the Taken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditResponse) SetTaken(taken *bool) {
	r.Taken = taken
	r.require(redditResponseFieldTaken)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditResponse) SetError(error *string) {
	r.Error = error
	r.require(redditResponseFieldError)
}

// SetExtraData sets the ExtraData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RedditResponse) SetExtraData(extraData *RedditExtraData) {
	r.ExtraData = extraData
	r.require(redditResponseFieldExtraData)
}

func (r *RedditResponse) UnmarshalJSON(data []byte) error {
	type embed RedditResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RedditResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.ExtraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RedditResponse) MarshalJSON() ([]byte, error) {
	type embed RedditResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, r.ExtraProperties)
}

func (r *RedditResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
