// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	profileSteamRequestFieldUsername = big.NewInt(1 << 0)
)

type ProfileSteamRequest struct {
	// The Steam username.
	Username string `json:"-" url:"username"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProfileSteamRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProfileSteamRequest) SetUsername(username string) {
	p.Username = username
	p.require(profileSteamRequestFieldUsername)
}

var (
	steamExtraDataFieldUsername     = big.NewInt(1 << 0)
	steamExtraDataFieldDisplayName  = big.NewInt(1 << 1)
	steamExtraDataFieldRealName     = big.NewInt(1 << 2)
	steamExtraDataFieldProfileURL   = big.NewInt(1 << 3)
	steamExtraDataFieldAvatarURL    = big.NewInt(1 << 4)
	steamExtraDataFieldProfileState = big.NewInt(1 << 5)
	steamExtraDataFieldVisibility   = big.NewInt(1 << 6)
	steamExtraDataFieldTimeCreated  = big.NewInt(1 << 7)
	steamExtraDataFieldLastLogoff   = big.NewInt(1 << 8)
	steamExtraDataFieldCountryCode  = big.NewInt(1 << 9)
)

type SteamExtraData struct {
	// Steam username.
	Username *string `json:"Username,omitempty" url:"Username,omitempty"`
	// Profile name.
	DisplayName *string `json:"DisplayName,omitempty" url:"DisplayName,omitempty"`
	// Real name, if public.
	RealName *string `json:"RealName,omitempty" url:"RealName,omitempty"`
	// Profile link.
	ProfileURL *string `json:"ProfileUrl,omitempty" url:"ProfileUrl,omitempty"`
	// Avatar.
	AvatarURL *string `json:"AvatarUrl,omitempty" url:"AvatarUrl,omitempty"`
	// 1 when the profile is set up.
	ProfileState *float64 `json:"ProfileState,omitempty" url:"ProfileState,omitempty"`
	// 3 = public, 1 = private.
	Visibility *float64 `json:"Visibility,omitempty" url:"Visibility,omitempty"`
	// Account creation (Unix time).
	TimeCreated *float64 `json:"TimeCreated,omitempty" url:"TimeCreated,omitempty"`
	// Last sign-off (Unix time).
	LastLogoff *float64 `json:"LastLogoff,omitempty" url:"LastLogoff,omitempty"`
	// Country, if public.
	CountryCode *string `json:"CountryCode,omitempty" url:"CountryCode,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (s *SteamExtraData) GetUsername() *string {
	if s == nil {
		return nil
	}
	return s.Username
}

func (s *SteamExtraData) GetDisplayName() *string {
	if s == nil {
		return nil
	}
	return s.DisplayName
}

func (s *SteamExtraData) GetRealName() *string {
	if s == nil {
		return nil
	}
	return s.RealName
}

func (s *SteamExtraData) GetProfileURL() *string {
	if s == nil {
		return nil
	}
	return s.ProfileURL
}

func (s *SteamExtraData) GetAvatarURL() *string {
	if s == nil {
		return nil
	}
	return s.AvatarURL
}

func (s *SteamExtraData) GetProfileState() *float64 {
	if s == nil {
		return nil
	}
	return s.ProfileState
}

func (s *SteamExtraData) GetVisibility() *float64 {
	if s == nil {
		return nil
	}
	return s.Visibility
}

func (s *SteamExtraData) GetTimeCreated() *float64 {
	if s == nil {
		return nil
	}
	return s.TimeCreated
}

func (s *SteamExtraData) GetLastLogoff() *float64 {
	if s == nil {
		return nil
	}
	return s.LastLogoff
}

func (s *SteamExtraData) GetCountryCode() *string {
	if s == nil {
		return nil
	}
	return s.CountryCode
}

func (s *SteamExtraData) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.ExtraProperties
}

func (s *SteamExtraData) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetUsername(username *string) {
	s.Username = username
	s.require(steamExtraDataFieldUsername)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetDisplayName(displayName *string) {
	s.DisplayName = displayName
	s.require(steamExtraDataFieldDisplayName)
}

// SetRealName sets the RealName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetRealName(realName *string) {
	s.RealName = realName
	s.require(steamExtraDataFieldRealName)
}

// SetProfileURL sets the ProfileURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetProfileURL(profileURL *string) {
	s.ProfileURL = profileURL
	s.require(steamExtraDataFieldProfileURL)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetAvatarURL(avatarURL *string) {
	s.AvatarURL = avatarURL
	s.require(steamExtraDataFieldAvatarURL)
}

// SetProfileState sets the ProfileState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetProfileState(profileState *float64) {
	s.ProfileState = profileState
	s.require(steamExtraDataFieldProfileState)
}

// SetVisibility sets the Visibility field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetVisibility(visibility *float64) {
	s.Visibility = visibility
	s.require(steamExtraDataFieldVisibility)
}

// SetTimeCreated sets the TimeCreated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetTimeCreated(timeCreated *float64) {
	s.TimeCreated = timeCreated
	s.require(steamExtraDataFieldTimeCreated)
}

// SetLastLogoff sets the LastLogoff field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetLastLogoff(lastLogoff *float64) {
	s.LastLogoff = lastLogoff
	s.require(steamExtraDataFieldLastLogoff)
}

// SetCountryCode sets the CountryCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamExtraData) SetCountryCode(countryCode *string) {
	s.CountryCode = countryCode
	s.require(steamExtraDataFieldCountryCode)
}

func (s *SteamExtraData) UnmarshalJSON(data []byte) error {
	type embed SteamExtraData
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SteamExtraData(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.ExtraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SteamExtraData) MarshalJSON() ([]byte, error) {
	type embed SteamExtraData
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, s.ExtraProperties)
}

func (s *SteamExtraData) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// `taken` is `true` when the account exists. `ExtraData` holds what the profile shows publicly; a field the profile does not have is left out. When the lookup could not be completed, `taken` is `false` and `error` says why (for example `rate_limited`, try again later).
var (
	steamResponseFieldTaken     = big.NewInt(1 << 0)
	steamResponseFieldError     = big.NewInt(1 << 1)
	steamResponseFieldExtraData = big.NewInt(1 << 2)
)

type SteamResponse struct {
	// Whether an account with this username exists.
	Taken *bool `json:"taken,omitempty" url:"taken,omitempty"`
	// Present only when the lookup could not be completed.
	Error     *string         `json:"error,omitempty" url:"error,omitempty"`
	ExtraData *SteamExtraData `json:"ExtraData,omitempty" url:"ExtraData,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (s *SteamResponse) GetTaken() *bool {
	if s == nil {
		return nil
	}
	return s.Taken
}

func (s *SteamResponse) GetError() *string {
	if s == nil {
		return nil
	}
	return s.Error
}

func (s *SteamResponse) GetExtraData() *SteamExtraData {
	if s == nil {
		return nil
	}
	return s.ExtraData
}

func (s *SteamResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.ExtraProperties
}

func (s *SteamResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetTaken sets the Taken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamResponse) SetTaken(taken *bool) {
	s.Taken = taken
	s.require(steamResponseFieldTaken)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamResponse) SetError(error *string) {
	s.Error = error
	s.require(steamResponseFieldError)
}

// SetExtraData sets the ExtraData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SteamResponse) SetExtraData(extraData *SteamExtraData) {
	s.ExtraData = extraData
	s.require(steamResponseFieldExtraData)
}

func (s *SteamResponse) UnmarshalJSON(data []byte) error {
	type embed SteamResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SteamResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.ExtraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SteamResponse) MarshalJSON() ([]byte, error) {
	type embed SteamResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, s.ExtraProperties)
}

func (s *SteamResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
