// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersProfileSteamRequest(t *testing.T) {
	t.Run("SetUsername", func(t *testing.T) {
		obj := &ProfileSteamRequest{}
		var fernTestValueUsername string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProfileSteamRequest(t *testing.T) {
	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProfileSteamRequest{}
		var fernTestValueUsername string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSteamExtraData(t *testing.T) {
	t.Run("SetUsername", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueUsername *string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueDisplayName *string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRealName", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueRealName *string
		obj.SetRealName(fernTestValueRealName)
		assert.Equal(t, fernTestValueRealName, obj.RealName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProfileURL", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueProfileURL *string
		obj.SetProfileURL(fernTestValueProfileURL)
		assert.Equal(t, fernTestValueProfileURL, obj.ProfileURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAvatarURL", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueAvatarURL *string
		obj.SetAvatarURL(fernTestValueAvatarURL)
		assert.Equal(t, fernTestValueAvatarURL, obj.AvatarURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProfileState", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueProfileState *float64
		obj.SetProfileState(fernTestValueProfileState)
		assert.Equal(t, fernTestValueProfileState, obj.ProfileState)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVisibility", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueVisibility *float64
		obj.SetVisibility(fernTestValueVisibility)
		assert.Equal(t, fernTestValueVisibility, obj.Visibility)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimeCreated", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueTimeCreated *float64
		obj.SetTimeCreated(fernTestValueTimeCreated)
		assert.Equal(t, fernTestValueTimeCreated, obj.TimeCreated)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLastLogoff", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueLastLogoff *float64
		obj.SetLastLogoff(fernTestValueLastLogoff)
		assert.Equal(t, fernTestValueLastLogoff, obj.LastLogoff)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCountryCode", func(t *testing.T) {
		obj := &SteamExtraData{}
		var fernTestValueCountryCode *string
		obj.SetCountryCode(fernTestValueCountryCode)
		assert.Equal(t, fernTestValueCountryCode, obj.CountryCode)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSteamExtraData(t *testing.T) {
	t.Run("GetUsername", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *string
		obj.Username = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsername(), "getter should return the property value")
	})

	t.Run("GetUsername_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.Username = nil

		// Act & Assert
		assert.Nil(t, obj.GetUsername(), "getter should return nil when property is nil")
	})

	t.Run("GetUsername_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsername() // Should return zero value
	})

	t.Run("GetDisplayName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *string
		obj.DisplayName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDisplayName(), "getter should return the property value")
	})

	t.Run("GetDisplayName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.DisplayName = nil

		// Act & Assert
		assert.Nil(t, obj.GetDisplayName(), "getter should return nil when property is nil")
	})

	t.Run("GetDisplayName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisplayName() // Should return zero value
	})

	t.Run("GetRealName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *string
		obj.RealName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRealName(), "getter should return the property value")
	})

	t.Run("GetRealName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.RealName = nil

		// Act & Assert
		assert.Nil(t, obj.GetRealName(), "getter should return nil when property is nil")
	})

	t.Run("GetRealName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRealName() // Should return zero value
	})

	t.Run("GetProfileURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *string
		obj.ProfileURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProfileURL(), "getter should return the property value")
	})

	t.Run("GetProfileURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.ProfileURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetProfileURL(), "getter should return nil when property is nil")
	})

	t.Run("GetProfileURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProfileURL() // Should return zero value
	})

	t.Run("GetAvatarURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *string
		obj.AvatarURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAvatarURL(), "getter should return the property value")
	})

	t.Run("GetAvatarURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.AvatarURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetAvatarURL(), "getter should return nil when property is nil")
	})

	t.Run("GetAvatarURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAvatarURL() // Should return zero value
	})

	t.Run("GetProfileState", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *float64
		obj.ProfileState = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProfileState(), "getter should return the property value")
	})

	t.Run("GetProfileState_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.ProfileState = nil

		// Act & Assert
		assert.Nil(t, obj.GetProfileState(), "getter should return nil when property is nil")
	})

	t.Run("GetProfileState_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProfileState() // Should return zero value
	})

	t.Run("GetVisibility", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *float64
		obj.Visibility = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVisibility(), "getter should return the property value")
	})

	t.Run("GetVisibility_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.Visibility = nil

		// Act & Assert
		assert.Nil(t, obj.GetVisibility(), "getter should return nil when property is nil")
	})

	t.Run("GetVisibility_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVisibility() // Should return zero value
	})

	t.Run("GetTimeCreated", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *float64
		obj.TimeCreated = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimeCreated(), "getter should return the property value")
	})

	t.Run("GetTimeCreated_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.TimeCreated = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimeCreated(), "getter should return nil when property is nil")
	})

	t.Run("GetTimeCreated_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimeCreated() // Should return zero value
	})

	t.Run("GetLastLogoff", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *float64
		obj.LastLogoff = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastLogoff(), "getter should return the property value")
	})

	t.Run("GetLastLogoff_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.LastLogoff = nil

		// Act & Assert
		assert.Nil(t, obj.GetLastLogoff(), "getter should return nil when property is nil")
	})

	t.Run("GetLastLogoff_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastLogoff() // Should return zero value
	})

	t.Run("GetCountryCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var expected *string
		obj.CountryCode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCountryCode(), "getter should return the property value")
	})

	t.Run("GetCountryCode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		obj.CountryCode = nil

		// Act & Assert
		assert.Nil(t, obj.GetCountryCode(), "getter should return nil when property is nil")
	})

	t.Run("GetCountryCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCountryCode() // Should return zero value
	})

}

func TestSettersMarkExplicitSteamExtraData(t *testing.T) {
	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueUsername *string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueDisplayName *string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRealName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueRealName *string

		// Act
		obj.SetRealName(fernTestValueRealName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProfileURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueProfileURL *string

		// Act
		obj.SetProfileURL(fernTestValueProfileURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAvatarURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueAvatarURL *string

		// Act
		obj.SetAvatarURL(fernTestValueAvatarURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProfileState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueProfileState *float64

		// Act
		obj.SetProfileState(fernTestValueProfileState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVisibility_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueVisibility *float64

		// Act
		obj.SetVisibility(fernTestValueVisibility)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimeCreated_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueTimeCreated *float64

		// Act
		obj.SetTimeCreated(fernTestValueTimeCreated)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLastLogoff_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueLastLogoff *float64

		// Act
		obj.SetLastLogoff(fernTestValueLastLogoff)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCountryCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}
		var fernTestValueCountryCode *string

		// Act
		obj.SetCountryCode(fernTestValueCountryCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSteamResponse(t *testing.T) {
	t.Run("SetTaken", func(t *testing.T) {
		obj := &SteamResponse{}
		var fernTestValueTaken *bool
		obj.SetTaken(fernTestValueTaken)
		assert.Equal(t, fernTestValueTaken, obj.Taken)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetError", func(t *testing.T) {
		obj := &SteamResponse{}
		var fernTestValueError *string
		obj.SetError(fernTestValueError)
		assert.Equal(t, fernTestValueError, obj.Error)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExtraData", func(t *testing.T) {
		obj := &SteamResponse{}
		var fernTestValueExtraData *SteamExtraData
		obj.SetExtraData(fernTestValueExtraData)
		assert.Equal(t, fernTestValueExtraData, obj.ExtraData)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSteamResponse(t *testing.T) {
	t.Run("GetTaken", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}
		var expected *bool
		obj.Taken = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTaken(), "getter should return the property value")
	})

	t.Run("GetTaken_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}
		obj.Taken = nil

		// Act & Assert
		assert.Nil(t, obj.GetTaken(), "getter should return nil when property is nil")
	})

	t.Run("GetTaken_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTaken() // Should return zero value
	})

	t.Run("GetError", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}
		var expected *string
		obj.Error = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetError(), "getter should return the property value")
	})

	t.Run("GetError_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}
		obj.Error = nil

		// Act & Assert
		assert.Nil(t, obj.GetError(), "getter should return nil when property is nil")
	})

	t.Run("GetError_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetError() // Should return zero value
	})

	t.Run("GetExtraData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}
		var expected *SteamExtraData
		obj.ExtraData = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExtraData(), "getter should return the property value")
	})

	t.Run("GetExtraData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}
		obj.ExtraData = nil

		// Act & Assert
		assert.Nil(t, obj.GetExtraData(), "getter should return nil when property is nil")
	})

	t.Run("GetExtraData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExtraData() // Should return zero value
	})

}

func TestSettersMarkExplicitSteamResponse(t *testing.T) {
	t.Run("SetTaken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}
		var fernTestValueTaken *bool

		// Act
		obj.SetTaken(fernTestValueTaken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetError_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}
		var fernTestValueError *string

		// Act
		obj.SetError(fernTestValueError)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExtraData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}
		var fernTestValueExtraData *SteamExtraData

		// Act
		obj.SetExtraData(fernTestValueExtraData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingSteamExtraData(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamExtraData{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SteamExtraData
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SteamExtraData
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SteamExtraData
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingSteamResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SteamResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SteamResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SteamResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SteamResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringSteamExtraData(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SteamExtraData{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringSteamResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SteamResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesSteamExtraData(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SteamExtraData{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamExtraData
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesSteamResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SteamResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SteamResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
