// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	resolveShareLinkTiktokRequestFieldLink = big.NewInt(1 << 0)
)

type ResolveShareLinkTiktokRequest struct {
	// A TikTok share link. `url` or `query` are accepted as well.
	Link string `json:"-" url:"link"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ResolveShareLinkTiktokRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetLink sets the Link field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveShareLinkTiktokRequest) SetLink(link string) {
	r.Link = link
	r.require(resolveShareLinkTiktokRequestFieldLink)
}

var (
	tiktokResolverResponseFieldSuccess   = big.NewInt(1 << 0)
	tiktokResolverResponseFieldSharer    = big.NewInt(1 << 1)
	tiktokResolverResponseFieldShareInfo = big.NewInt(1 << 2)
	tiktokResolverResponseFieldVideo     = big.NewInt(1 << 3)
)

type TiktokResolverResponse struct {
	// `true` when resolved.
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// The account that shared the link: `username`, `nickname`, `avatar`, `region`, `language`, `account_created`, `follower_count`, `following_count`, `heart_count`, `video_count`, `bio`, `verified`, `private`. `resolved_via` is `sec_uid` for the sharer, or `video_author` when only the video's author could be identified.
	Sharer map[string]any `json:"sharer,omitempty" url:"sharer,omitempty"`
	// The share: `shared_from`, `share_time`, `device`, `language`, `region`, `account_created`.
	ShareInfo map[string]any `json:"share_info,omitempty" url:"share_info,omitempty"`
	// The video: `full_url`, `video_id`, `video_created`, `type`, `author_username`.
	Video map[string]any `json:"video,omitempty" url:"video,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (t *TiktokResolverResponse) GetSuccess() *bool {
	if t == nil {
		return nil
	}
	return t.Success
}

func (t *TiktokResolverResponse) GetSharer() map[string]any {
	if t == nil {
		return nil
	}
	return t.Sharer
}

func (t *TiktokResolverResponse) GetShareInfo() map[string]any {
	if t == nil {
		return nil
	}
	return t.ShareInfo
}

func (t *TiktokResolverResponse) GetVideo() map[string]any {
	if t == nil {
		return nil
	}
	return t.Video
}

func (t *TiktokResolverResponse) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.ExtraProperties
}

func (t *TiktokResolverResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TiktokResolverResponse) SetSuccess(success *bool) {
	t.Success = success
	t.require(tiktokResolverResponseFieldSuccess)
}

// SetSharer sets the Sharer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TiktokResolverResponse) SetSharer(sharer map[string]any) {
	t.Sharer = sharer
	t.require(tiktokResolverResponseFieldSharer)
}

// SetShareInfo sets the ShareInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TiktokResolverResponse) SetShareInfo(shareInfo map[string]any) {
	t.ShareInfo = shareInfo
	t.require(tiktokResolverResponseFieldShareInfo)
}

// SetVideo sets the Video field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TiktokResolverResponse) SetVideo(video map[string]any) {
	t.Video = video
	t.require(tiktokResolverResponseFieldVideo)
}

func (t *TiktokResolverResponse) UnmarshalJSON(data []byte) error {
	type embed TiktokResolverResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TiktokResolverResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.ExtraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TiktokResolverResponse) MarshalJSON() ([]byte, error) {
	type embed TiktokResolverResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, t.ExtraProperties)
}

func (t *TiktokResolverResponse) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
