// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersResolveShareLinkTiktokRequest(t *testing.T) {
	t.Run("SetLink", func(t *testing.T) {
		obj := &ResolveShareLinkTiktokRequest{}
		var fernTestValueLink string
		obj.SetLink(fernTestValueLink)
		assert.Equal(t, fernTestValueLink, obj.Link)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitResolveShareLinkTiktokRequest(t *testing.T) {
	t.Run("SetLink_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResolveShareLinkTiktokRequest{}
		var fernTestValueLink string

		// Act
		obj.SetLink(fernTestValueLink)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTiktokResolverResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &TiktokResolverResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSharer", func(t *testing.T) {
		obj := &TiktokResolverResponse{}
		var fernTestValueSharer map[string]any
		obj.SetSharer(fernTestValueSharer)
		assert.Equal(t, fernTestValueSharer, obj.Sharer)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetShareInfo", func(t *testing.T) {
		obj := &TiktokResolverResponse{}
		var fernTestValueShareInfo map[string]any
		obj.SetShareInfo(fernTestValueShareInfo)
		assert.Equal(t, fernTestValueShareInfo, obj.ShareInfo)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVideo", func(t *testing.T) {
		obj := &TiktokResolverResponse{}
		var fernTestValueVideo map[string]any
		obj.SetVideo(fernTestValueVideo)
		assert.Equal(t, fernTestValueVideo, obj.Video)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTiktokResolverResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TiktokResolverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetSharer", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		var expected map[string]any
		obj.Sharer = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSharer(), "getter should return the property value")
	})

	t.Run("GetSharer_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		obj.Sharer = nil

		// Act & Assert
		assert.Nil(t, obj.GetSharer(), "getter should return nil when property is nil")
	})

	t.Run("GetSharer_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TiktokResolverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSharer() // Should return zero value
	})

	t.Run("GetShareInfo", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		var expected map[string]any
		obj.ShareInfo = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetShareInfo(), "getter should return the property value")
	})

	t.Run("GetShareInfo_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		obj.ShareInfo = nil

		// Act & Assert
		assert.Nil(t, obj.GetShareInfo(), "getter should return nil when property is nil")
	})

	t.Run("GetShareInfo_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TiktokResolverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetShareInfo() // Should return zero value
	})

	t.Run("GetVideo", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		var expected map[string]any
		obj.Video = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVideo(), "getter should return the property value")
	})

	t.Run("GetVideo_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		obj.Video = nil

		// Act & Assert
		assert.Nil(t, obj.GetVideo(), "getter should return nil when property is nil")
	})

	t.Run("GetVideo_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TiktokResolverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVideo() // Should return zero value
	})

}

func TestSettersMarkExplicitTiktokResolverResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSharer_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		var fernTestValueSharer map[string]any

		// Act
		obj.SetSharer(fernTestValueSharer)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetShareInfo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		var fernTestValueShareInfo map[string]any

		// Act
		obj.SetShareInfo(fernTestValueShareInfo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVideo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}
		var fernTestValueVideo map[string]any

		// Act
		obj.SetVideo(fernTestValueVideo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingTiktokResolverResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TiktokResolverResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TiktokResolverResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TiktokResolverResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TiktokResolverResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringTiktokResolverResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TiktokResolverResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TiktokResolverResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesTiktokResolverResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TiktokResolverResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TiktokResolverResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
