// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersProfileTwitchRequest(t *testing.T) {
	t.Run("SetUsername", func(t *testing.T) {
		obj := &ProfileTwitchRequest{}
		var fernTestValueUsername string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitProfileTwitchRequest(t *testing.T) {
	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ProfileTwitchRequest{}
		var fernTestValueUsername string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTwitchExtraData(t *testing.T) {
	t.Run("SetUsername", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueUsername *string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueDisplayName *string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserID", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueUserID *string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDescription", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueDescription *string
		obj.SetDescription(fernTestValueDescription)
		assert.Equal(t, fernTestValueDescription, obj.Description)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProfilePicURL", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueProfilePicURL *string
		obj.SetProfilePicURL(fernTestValueProfilePicURL)
		assert.Equal(t, fernTestValueProfilePicURL, obj.ProfilePicURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFollowers", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueFollowers *float64
		obj.SetFollowers(fernTestValueFollowers)
		assert.Equal(t, fernTestValueFollowers, obj.Followers)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueCreatedAt *string
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBroadcasterType", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueBroadcasterType *string
		obj.SetBroadcasterType(fernTestValueBroadcasterType)
		assert.Equal(t, fernTestValueBroadcasterType, obj.BroadcasterType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBanned", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueBanned *bool
		obj.SetBanned(fernTestValueBanned)
		assert.Equal(t, fernTestValueBanned, obj.Banned)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsPartner", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueIsPartner *bool
		obj.SetIsPartner(fernTestValueIsPartner)
		assert.Equal(t, fernTestValueIsPartner, obj.IsPartner)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsAffiliate", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueIsAffiliate *bool
		obj.SetIsAffiliate(fernTestValueIsAffiliate)
		assert.Equal(t, fernTestValueIsAffiliate, obj.IsAffiliate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProfileURL", func(t *testing.T) {
		obj := &TwitchExtraData{}
		var fernTestValueProfileURL *string
		obj.SetProfileURL(fernTestValueProfileURL)
		assert.Equal(t, fernTestValueProfileURL, obj.ProfileURL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTwitchExtraData(t *testing.T) {
	t.Run("GetUsername", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *string
		obj.Username = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsername(), "getter should return the property value")
	})

	t.Run("GetUsername_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.Username = nil

		// Act & Assert
		assert.Nil(t, obj.GetUsername(), "getter should return nil when property is nil")
	})

	t.Run("GetUsername_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsername() // Should return zero value
	})

	t.Run("GetDisplayName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *string
		obj.DisplayName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDisplayName(), "getter should return the property value")
	})

	t.Run("GetDisplayName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.DisplayName = nil

		// Act & Assert
		assert.Nil(t, obj.GetDisplayName(), "getter should return nil when property is nil")
	})

	t.Run("GetDisplayName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisplayName() // Should return zero value
	})

	t.Run("GetUserID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *string
		obj.UserID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserID(), "getter should return the property value")
	})

	t.Run("GetUserID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.UserID = nil

		// Act & Assert
		assert.Nil(t, obj.GetUserID(), "getter should return nil when property is nil")
	})

	t.Run("GetUserID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserID() // Should return zero value
	})

	t.Run("GetDescription", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *string
		obj.Description = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDescription(), "getter should return the property value")
	})

	t.Run("GetDescription_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.Description = nil

		// Act & Assert
		assert.Nil(t, obj.GetDescription(), "getter should return nil when property is nil")
	})

	t.Run("GetDescription_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDescription() // Should return zero value
	})

	t.Run("GetProfilePicURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *string
		obj.ProfilePicURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProfilePicURL(), "getter should return the property value")
	})

	t.Run("GetProfilePicURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.ProfilePicURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetProfilePicURL(), "getter should return nil when property is nil")
	})

	t.Run("GetProfilePicURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProfilePicURL() // Should return zero value
	})

	t.Run("GetFollowers", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *float64
		obj.Followers = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFollowers(), "getter should return the property value")
	})

	t.Run("GetFollowers_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.Followers = nil

		// Act & Assert
		assert.Nil(t, obj.GetFollowers(), "getter should return nil when property is nil")
	})

	t.Run("GetFollowers_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFollowers() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *string
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.CreatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetBroadcasterType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *string
		obj.BroadcasterType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBroadcasterType(), "getter should return the property value")
	})

	t.Run("GetBroadcasterType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.BroadcasterType = nil

		// Act & Assert
		assert.Nil(t, obj.GetBroadcasterType(), "getter should return nil when property is nil")
	})

	t.Run("GetBroadcasterType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBroadcasterType() // Should return zero value
	})

	t.Run("GetBanned", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *bool
		obj.Banned = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBanned(), "getter should return the property value")
	})

	t.Run("GetBanned_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.Banned = nil

		// Act & Assert
		assert.Nil(t, obj.GetBanned(), "getter should return nil when property is nil")
	})

	t.Run("GetBanned_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBanned() // Should return zero value
	})

	t.Run("GetIsPartner", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *bool
		obj.IsPartner = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsPartner(), "getter should return the property value")
	})

	t.Run("GetIsPartner_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.IsPartner = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsPartner(), "getter should return nil when property is nil")
	})

	t.Run("GetIsPartner_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsPartner() // Should return zero value
	})

	t.Run("GetIsAffiliate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *bool
		obj.IsAffiliate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsAffiliate(), "getter should return the property value")
	})

	t.Run("GetIsAffiliate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.IsAffiliate = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsAffiliate(), "getter should return nil when property is nil")
	})

	t.Run("GetIsAffiliate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsAffiliate() // Should return zero value
	})

	t.Run("GetProfileURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var expected *string
		obj.ProfileURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProfileURL(), "getter should return the property value")
	})

	t.Run("GetProfileURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		obj.ProfileURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetProfileURL(), "getter should return nil when property is nil")
	})

	t.Run("GetProfileURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProfileURL() // Should return zero value
	})

}

func TestSettersMarkExplicitTwitchExtraData(t *testing.T) {
	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueUsername *string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueDisplayName *string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueUserID *string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDescription_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueDescription *string

		// Act
		obj.SetDescription(fernTestValueDescription)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProfilePicURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueProfilePicURL *string

		// Act
		obj.SetProfilePicURL(fernTestValueProfilePicURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFollowers_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueFollowers *float64

		// Act
		obj.SetFollowers(fernTestValueFollowers)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueCreatedAt *string

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBroadcasterType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueBroadcasterType *string

		// Act
		obj.SetBroadcasterType(fernTestValueBroadcasterType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBanned_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueBanned *bool

		// Act
		obj.SetBanned(fernTestValueBanned)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsPartner_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueIsPartner *bool

		// Act
		obj.SetIsPartner(fernTestValueIsPartner)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsAffiliate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueIsAffiliate *bool

		// Act
		obj.SetIsAffiliate(fernTestValueIsAffiliate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProfileURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}
		var fernTestValueProfileURL *string

		// Act
		obj.SetProfileURL(fernTestValueProfileURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTwitchResponse(t *testing.T) {
	t.Run("SetTaken", func(t *testing.T) {
		obj := &TwitchResponse{}
		var fernTestValueTaken *bool
		obj.SetTaken(fernTestValueTaken)
		assert.Equal(t, fernTestValueTaken, obj.Taken)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetError", func(t *testing.T) {
		obj := &TwitchResponse{}
		var fernTestValueError *string
		obj.SetError(fernTestValueError)
		assert.Equal(t, fernTestValueError, obj.Error)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExtraData", func(t *testing.T) {
		obj := &TwitchResponse{}
		var fernTestValueExtraData *TwitchExtraData
		obj.SetExtraData(fernTestValueExtraData)
		assert.Equal(t, fernTestValueExtraData, obj.ExtraData)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTwitchResponse(t *testing.T) {
	t.Run("GetTaken", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}
		var expected *bool
		obj.Taken = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTaken(), "getter should return the property value")
	})

	t.Run("GetTaken_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}
		obj.Taken = nil

		// Act & Assert
		assert.Nil(t, obj.GetTaken(), "getter should return nil when property is nil")
	})

	t.Run("GetTaken_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTaken() // Should return zero value
	})

	t.Run("GetError", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}
		var expected *string
		obj.Error = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetError(), "getter should return the property value")
	})

	t.Run("GetError_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}
		obj.Error = nil

		// Act & Assert
		assert.Nil(t, obj.GetError(), "getter should return nil when property is nil")
	})

	t.Run("GetError_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetError() // Should return zero value
	})

	t.Run("GetExtraData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}
		var expected *TwitchExtraData
		obj.ExtraData = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExtraData(), "getter should return the property value")
	})

	t.Run("GetExtraData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}
		obj.ExtraData = nil

		// Act & Assert
		assert.Nil(t, obj.GetExtraData(), "getter should return nil when property is nil")
	})

	t.Run("GetExtraData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExtraData() // Should return zero value
	})

}

func TestSettersMarkExplicitTwitchResponse(t *testing.T) {
	t.Run("SetTaken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}
		var fernTestValueTaken *bool

		// Act
		obj.SetTaken(fernTestValueTaken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetError_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}
		var fernTestValueError *string

		// Act
		obj.SetError(fernTestValueError)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExtraData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}
		var fernTestValueExtraData *TwitchExtraData

		// Act
		obj.SetExtraData(fernTestValueExtraData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingTwitchExtraData(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchExtraData{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TwitchExtraData
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TwitchExtraData
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TwitchExtraData
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingTwitchResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TwitchResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TwitchResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TwitchResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TwitchResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringTwitchExtraData(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TwitchExtraData{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringTwitchResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TwitchResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesTwitchExtraData(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TwitchExtraData{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchExtraData
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesTwitchResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TwitchResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TwitchResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
