// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	profileTwitchRequestFieldUsername = big.NewInt(1 << 0)
)

type ProfileTwitchRequest struct {
	// The Twitch username.
	Username string `json:"-" url:"username"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProfileTwitchRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProfileTwitchRequest) SetUsername(username string) {
	p.Username = username
	p.require(profileTwitchRequestFieldUsername)
}

var (
	twitchExtraDataFieldUsername        = big.NewInt(1 << 0)
	twitchExtraDataFieldDisplayName     = big.NewInt(1 << 1)
	twitchExtraDataFieldUserID          = big.NewInt(1 << 2)
	twitchExtraDataFieldDescription     = big.NewInt(1 << 3)
	twitchExtraDataFieldProfilePicURL   = big.NewInt(1 << 4)
	twitchExtraDataFieldFollowers       = big.NewInt(1 << 5)
	twitchExtraDataFieldCreatedAt       = big.NewInt(1 << 6)
	twitchExtraDataFieldBroadcasterType = big.NewInt(1 << 7)
	twitchExtraDataFieldBanned          = big.NewInt(1 << 8)
	twitchExtraDataFieldIsPartner       = big.NewInt(1 << 9)
	twitchExtraDataFieldIsAffiliate     = big.NewInt(1 << 10)
	twitchExtraDataFieldProfileURL      = big.NewInt(1 << 11)
)

type TwitchExtraData struct {
	// Login name.
	Username *string `json:"Username,omitempty" url:"Username,omitempty"`
	// Display name.
	DisplayName *string `json:"DisplayName,omitempty" url:"DisplayName,omitempty"`
	// Twitch user ID.
	UserID *string `json:"UserID,omitempty" url:"UserID,omitempty"`
	// Bio.
	Description *string `json:"Description,omitempty" url:"Description,omitempty"`
	// Profile picture.
	ProfilePicURL *string `json:"ProfilePicUrl,omitempty" url:"ProfilePicUrl,omitempty"`
	// Followers.
	Followers *float64 `json:"Followers,omitempty" url:"Followers,omitempty"`
	// Account creation.
	CreatedAt *string `json:"CreatedAt,omitempty" url:"CreatedAt,omitempty"`
	// `partner`, `affiliate` or empty.
	BroadcasterType *string `json:"BroadcasterType,omitempty" url:"BroadcasterType,omitempty"`
	// Whether the account is suspended (`BanReason` then says why).
	Banned *bool `json:"Banned,omitempty" url:"Banned,omitempty"`
	// Twitch partner.
	IsPartner *bool `json:"IsPartner,omitempty" url:"IsPartner,omitempty"`
	// Twitch affiliate.
	IsAffiliate *bool `json:"IsAffiliate,omitempty" url:"IsAffiliate,omitempty"`
	// Channel link.
	ProfileURL *string `json:"ProfileUrl,omitempty" url:"ProfileUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (t *TwitchExtraData) GetUsername() *string {
	if t == nil {
		return nil
	}
	return t.Username
}

func (t *TwitchExtraData) GetDisplayName() *string {
	if t == nil {
		return nil
	}
	return t.DisplayName
}

func (t *TwitchExtraData) GetUserID() *string {
	if t == nil {
		return nil
	}
	return t.UserID
}

func (t *TwitchExtraData) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TwitchExtraData) GetProfilePicURL() *string {
	if t == nil {
		return nil
	}
	return t.ProfilePicURL
}

func (t *TwitchExtraData) GetFollowers() *float64 {
	if t == nil {
		return nil
	}
	return t.Followers
}

func (t *TwitchExtraData) GetCreatedAt() *string {
	if t == nil {
		return nil
	}
	return t.CreatedAt
}

func (t *TwitchExtraData) GetBroadcasterType() *string {
	if t == nil {
		return nil
	}
	return t.BroadcasterType
}

func (t *TwitchExtraData) GetBanned() *bool {
	if t == nil {
		return nil
	}
	return t.Banned
}

func (t *TwitchExtraData) GetIsPartner() *bool {
	if t == nil {
		return nil
	}
	return t.IsPartner
}

func (t *TwitchExtraData) GetIsAffiliate() *bool {
	if t == nil {
		return nil
	}
	return t.IsAffiliate
}

func (t *TwitchExtraData) GetProfileURL() *string {
	if t == nil {
		return nil
	}
	return t.ProfileURL
}

func (t *TwitchExtraData) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.ExtraProperties
}

func (t *TwitchExtraData) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetUsername(username *string) {
	t.Username = username
	t.require(twitchExtraDataFieldUsername)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetDisplayName(displayName *string) {
	t.DisplayName = displayName
	t.require(twitchExtraDataFieldDisplayName)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetUserID(userID *string) {
	t.UserID = userID
	t.require(twitchExtraDataFieldUserID)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetDescription(description *string) {
	t.Description = description
	t.require(twitchExtraDataFieldDescription)
}

// SetProfilePicURL sets the ProfilePicURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetProfilePicURL(profilePicURL *string) {
	t.ProfilePicURL = profilePicURL
	t.require(twitchExtraDataFieldProfilePicURL)
}

// SetFollowers sets the Followers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetFollowers(followers *float64) {
	t.Followers = followers
	t.require(twitchExtraDataFieldFollowers)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetCreatedAt(createdAt *string) {
	t.CreatedAt = createdAt
	t.require(twitchExtraDataFieldCreatedAt)
}

// SetBroadcasterType sets the BroadcasterType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetBroadcasterType(broadcasterType *string) {
	t.BroadcasterType = broadcasterType
	t.require(twitchExtraDataFieldBroadcasterType)
}

// SetBanned sets the Banned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetBanned(banned *bool) {
	t.Banned = banned
	t.require(twitchExtraDataFieldBanned)
}

// SetIsPartner sets the IsPartner field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetIsPartner(isPartner *bool) {
	t.IsPartner = isPartner
	t.require(twitchExtraDataFieldIsPartner)
}

// SetIsAffiliate sets the IsAffiliate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetIsAffiliate(isAffiliate *bool) {
	t.IsAffiliate = isAffiliate
	t.require(twitchExtraDataFieldIsAffiliate)
}

// SetProfileURL sets the ProfileURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchExtraData) SetProfileURL(profileURL *string) {
	t.ProfileURL = profileURL
	t.require(twitchExtraDataFieldProfileURL)
}

func (t *TwitchExtraData) UnmarshalJSON(data []byte) error {
	type embed TwitchExtraData
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TwitchExtraData(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.ExtraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TwitchExtraData) MarshalJSON() ([]byte, error) {
	type embed TwitchExtraData
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, t.ExtraProperties)
}

func (t *TwitchExtraData) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// `taken` is `true` when the account exists. `ExtraData` holds what the profile shows publicly; a field the profile does not have is left out. When the lookup could not be completed, `taken` is `false` and `error` says why (for example `rate_limited`, try again later).
var (
	twitchResponseFieldTaken     = big.NewInt(1 << 0)
	twitchResponseFieldError     = big.NewInt(1 << 1)
	twitchResponseFieldExtraData = big.NewInt(1 << 2)
)

type TwitchResponse struct {
	// Whether an account with this username exists.
	Taken *bool `json:"taken,omitempty" url:"taken,omitempty"`
	// Present only when the lookup could not be completed.
	Error     *string          `json:"error,omitempty" url:"error,omitempty"`
	ExtraData *TwitchExtraData `json:"ExtraData,omitempty" url:"ExtraData,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (t *TwitchResponse) GetTaken() *bool {
	if t == nil {
		return nil
	}
	return t.Taken
}

func (t *TwitchResponse) GetError() *string {
	if t == nil {
		return nil
	}
	return t.Error
}

func (t *TwitchResponse) GetExtraData() *TwitchExtraData {
	if t == nil {
		return nil
	}
	return t.ExtraData
}

func (t *TwitchResponse) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.ExtraProperties
}

func (t *TwitchResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTaken sets the Taken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchResponse) SetTaken(taken *bool) {
	t.Taken = taken
	t.require(twitchResponseFieldTaken)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchResponse) SetError(error *string) {
	t.Error = error
	t.require(twitchResponseFieldError)
}

// SetExtraData sets the ExtraData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitchResponse) SetExtraData(extraData *TwitchExtraData) {
	t.ExtraData = extraData
	t.require(twitchResponseFieldExtraData)
}

func (t *TwitchResponse) UnmarshalJSON(data []byte) error {
	type embed TwitchResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TwitchResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.ExtraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TwitchResponse) MarshalJSON() ([]byte, error) {
	type embed TwitchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, t.ExtraProperties)
}

func (t *TwitchResponse) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
