// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	queryVinRequestFieldOperation   = big.NewInt(1 << 0)
	queryVinRequestFieldQuery       = big.NewInt(1 << 1)
	queryVinRequestFieldModelYear   = big.NewInt(1 << 2)
	queryVinRequestFieldExtended    = big.NewInt(1 << 3)
	queryVinRequestFieldSearchType  = big.NewInt(1 << 4)
	queryVinRequestFieldYear        = big.NewInt(1 << 5)
	queryVinRequestFieldVehicleType = big.NewInt(1 << 6)
	queryVinRequestFieldMfrType     = big.NewInt(1 << 7)
	queryVinRequestFieldPage        = big.NewInt(1 << 8)
	queryVinRequestFieldPartsType   = big.NewInt(1 << 9)
	queryVinRequestFieldFromDate    = big.NewInt(1 << 10)
	queryVinRequestFieldToDate      = big.NewInt(1 << 11)
	queryVinRequestFieldMake        = big.NewInt(1 << 12)
	queryVinRequestFieldModel       = big.NewInt(1 << 13)
	queryVinRequestFieldUnits       = big.NewInt(1 << 14)
)

type QueryVinRequest struct {
	// `decode` (default), `batch`, `wmi`, `makes`, `manufacturers`, `variables` or `canadian`.
	Operation *QueryVinRequestType `json:"-" url:"type,omitempty"`
	// The VIN (`decode`), VINs separated by new lines, up to 50 (`batch`), a WMI (`wmi`), or the make / manufacturer / variable name the chosen `search_type` needs. Not needed for `makes`+`all`, `manufacturers`+`all`/`parts`, `variables`+`list` and `canadian`.
	Query *string `json:"-" url:"query,omitempty"`
	// `decode`: model year, improves accuracy.
	ModelYear *float64 `json:"-" url:"model_year,omitempty"`
	// `decode`: `true` for the extended field set.
	Extended *bool `json:"-" url:"extended,omitempty"`
	// `makes`: `all`, `manufacturer`, `vehicletype`, `models`, `vehicletypes`. `manufacturers`: `all`, `details`, `wmis`, `parts`. `variables`: `list`, `values`.
	SearchType *string `json:"-" url:"search_type,omitempty"`
	// `makes` with `manufacturer`/`models`, and `canadian`: model year.
	Year *float64 `json:"-" url:"year,omitempty"`
	// `makes`+`models` and `manufacturers`+`wmis`: vehicle type filter.
	VehicleType *string `json:"-" url:"vehicle_type,omitempty"`
	// `manufacturers`+`all`: manufacturer type filter.
	MfrType *string `json:"-" url:"mfr_type,omitempty"`
	// `manufacturers`+`all`/`parts`: page number.
	Page *float64 `json:"-" url:"page,omitempty"`
	// `manufacturers`+`parts`: CFR part, default `565`.
	PartsType *string `json:"-" url:"parts_type,omitempty"`
	// `manufacturers`+`parts`: start date (required there).
	FromDate *string `json:"-" url:"from_date,omitempty"`
	// `manufacturers`+`parts`: end date (required there).
	ToDate *string `json:"-" url:"to_date,omitempty"`
	// `canadian`: make.
	Make *string `json:"-" url:"make,omitempty"`
	// `canadian`: model.
	Model *string `json:"-" url:"model,omitempty"`
	// `canadian`: `Metric` (default) or `US`.
	Units *QueryVinRequestUnits `json:"-" url:"units,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (q *QueryVinRequest) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetOperation sets the Operation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetOperation(operation *QueryVinRequestType) {
	q.Operation = operation
	q.require(queryVinRequestFieldOperation)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetQuery(query *string) {
	q.Query = query
	q.require(queryVinRequestFieldQuery)
}

// SetModelYear sets the ModelYear field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetModelYear(modelYear *float64) {
	q.ModelYear = modelYear
	q.require(queryVinRequestFieldModelYear)
}

// SetExtended sets the Extended field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetExtended(extended *bool) {
	q.Extended = extended
	q.require(queryVinRequestFieldExtended)
}

// SetSearchType sets the SearchType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetSearchType(searchType *string) {
	q.SearchType = searchType
	q.require(queryVinRequestFieldSearchType)
}

// SetYear sets the Year field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetYear(year *float64) {
	q.Year = year
	q.require(queryVinRequestFieldYear)
}

// SetVehicleType sets the VehicleType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetVehicleType(vehicleType *string) {
	q.VehicleType = vehicleType
	q.require(queryVinRequestFieldVehicleType)
}

// SetMfrType sets the MfrType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetMfrType(mfrType *string) {
	q.MfrType = mfrType
	q.require(queryVinRequestFieldMfrType)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetPage(page *float64) {
	q.Page = page
	q.require(queryVinRequestFieldPage)
}

// SetPartsType sets the PartsType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetPartsType(partsType *string) {
	q.PartsType = partsType
	q.require(queryVinRequestFieldPartsType)
}

// SetFromDate sets the FromDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetFromDate(fromDate *string) {
	q.FromDate = fromDate
	q.require(queryVinRequestFieldFromDate)
}

// SetToDate sets the ToDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetToDate(toDate *string) {
	q.ToDate = toDate
	q.require(queryVinRequestFieldToDate)
}

// SetMake sets the Make field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetMake(make *string) {
	q.Make = make
	q.require(queryVinRequestFieldMake)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetModel(model *string) {
	q.Model = model
	q.require(queryVinRequestFieldModel)
}

// SetUnits sets the Units field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryVinRequest) SetUnits(units *QueryVinRequestUnits) {
	q.Units = units
	q.require(queryVinRequestFieldUnits)
}

// The decoder's answer for the chosen `type`, typically `{"Count": n, "Message": "...", "Results": [...]}`. Decoded VINs are cached for an hour.
var (
	vinResponseFieldCount   = big.NewInt(1 << 0)
	vinResponseFieldMessage = big.NewInt(1 << 1)
	vinResponseFieldResults = big.NewInt(1 << 2)
)

type VinResponse struct {
	Count   *int             `json:"Count,omitempty" url:"Count,omitempty"`
	Message *string          `json:"Message,omitempty" url:"Message,omitempty"`
	Results []map[string]any `json:"Results,omitempty" url:"Results,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (v *VinResponse) GetCount() *int {
	if v == nil {
		return nil
	}
	return v.Count
}

func (v *VinResponse) GetMessage() *string {
	if v == nil {
		return nil
	}
	return v.Message
}

func (v *VinResponse) GetResults() []map[string]any {
	if v == nil {
		return nil
	}
	return v.Results
}

func (v *VinResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.ExtraProperties
}

func (v *VinResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VinResponse) SetCount(count *int) {
	v.Count = count
	v.require(vinResponseFieldCount)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VinResponse) SetMessage(message *string) {
	v.Message = message
	v.require(vinResponseFieldMessage)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VinResponse) SetResults(results []map[string]any) {
	v.Results = results
	v.require(vinResponseFieldResults)
}

func (v *VinResponse) UnmarshalJSON(data []byte) error {
	type embed VinResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*v = VinResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.ExtraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VinResponse) MarshalJSON() ([]byte, error) {
	type embed VinResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, v.ExtraProperties)
}

func (v *VinResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type QueryVinRequestType string

const (
	QueryVinRequestTypeDecode        QueryVinRequestType = "decode"
	QueryVinRequestTypeBatch         QueryVinRequestType = "batch"
	QueryVinRequestTypeWmi           QueryVinRequestType = "wmi"
	QueryVinRequestTypeMakes         QueryVinRequestType = "makes"
	QueryVinRequestTypeManufacturers QueryVinRequestType = "manufacturers"
	QueryVinRequestTypeVariables     QueryVinRequestType = "variables"
	QueryVinRequestTypeCanadian      QueryVinRequestType = "canadian"
)

func NewQueryVinRequestTypeFromString(s string) (QueryVinRequestType, error) {
	switch s {
	case "decode":
		return QueryVinRequestTypeDecode, nil
	case "batch":
		return QueryVinRequestTypeBatch, nil
	case "wmi":
		return QueryVinRequestTypeWmi, nil
	case "makes":
		return QueryVinRequestTypeMakes, nil
	case "manufacturers":
		return QueryVinRequestTypeManufacturers, nil
	case "variables":
		return QueryVinRequestTypeVariables, nil
	case "canadian":
		return QueryVinRequestTypeCanadian, nil
	}
	var t QueryVinRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QueryVinRequestType) Ptr() *QueryVinRequestType {
	return &q
}

type QueryVinRequestUnits string

const (
	QueryVinRequestUnitsMetric QueryVinRequestUnits = "Metric"
	QueryVinRequestUnitsUs     QueryVinRequestUnits = "US"
)

func NewQueryVinRequestUnitsFromString(s string) (QueryVinRequestUnits, error) {
	switch s {
	case "Metric":
		return QueryVinRequestUnitsMetric, nil
	case "US":
		return QueryVinRequestUnitsUs, nil
	}
	var t QueryVinRequestUnits
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QueryVinRequestUnits) Ptr() *QueryVinRequestUnits {
	return &q
}
