// Code generated by Fern. DO NOT EDIT.

package osintcat

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	big "math/big"
)

var (
	profileXRequestFieldQuery = big.NewInt(1 << 0)
)

type ProfileXRequest struct {
	// The X username, with or without `@`.
	Query string `json:"-" url:"query"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProfileXRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProfileXRequest) SetQuery(query string) {
	p.Query = query
	p.require(profileXRequestFieldQuery)
}

var (
	twitterProfileFieldID           = big.NewInt(1 << 0)
	twitterProfileFieldUsername     = big.NewInt(1 << 1)
	twitterProfileFieldName         = big.NewInt(1 << 2)
	twitterProfileFieldCreatedAt    = big.NewInt(1 << 3)
	twitterProfileFieldFollowers    = big.NewInt(1 << 4)
	twitterProfileFieldFollowing    = big.NewInt(1 << 5)
	twitterProfileFieldTweetsCount  = big.NewInt(1 << 6)
	twitterProfileFieldDescription  = big.NewInt(1 << 7)
	twitterProfileFieldProfileImage = big.NewInt(1 << 8)
	twitterProfileFieldBannerImage  = big.NewInt(1 << 9)
	twitterProfileFieldVerified     = big.NewInt(1 << 10)
)

type TwitterProfile struct {
	// Account ID.
	ID *string `json:"id,omitempty" url:"id,omitempty"`
	// Handle.
	Username *string `json:"username,omitempty" url:"username,omitempty"`
	// Display name.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Account creation.
	CreatedAt *string `json:"created_at,omitempty" url:"created_at,omitempty"`
	// Followers.
	Followers *float64 `json:"followers,omitempty" url:"followers,omitempty"`
	// Following.
	Following *float64 `json:"following,omitempty" url:"following,omitempty"`
	// Posts.
	TweetsCount *float64 `json:"tweets_count,omitempty" url:"tweets_count,omitempty"`
	// Bio.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Profile picture.
	ProfileImage *string `json:"profile_image,omitempty" url:"profile_image,omitempty"`
	// Banner.
	BannerImage *string `json:"banner_image,omitempty" url:"banner_image,omitempty"`
	// Verified.
	Verified *bool `json:"verified,omitempty" url:"verified,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (t *TwitterProfile) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TwitterProfile) GetUsername() *string {
	if t == nil {
		return nil
	}
	return t.Username
}

func (t *TwitterProfile) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TwitterProfile) GetCreatedAt() *string {
	if t == nil {
		return nil
	}
	return t.CreatedAt
}

func (t *TwitterProfile) GetFollowers() *float64 {
	if t == nil {
		return nil
	}
	return t.Followers
}

func (t *TwitterProfile) GetFollowing() *float64 {
	if t == nil {
		return nil
	}
	return t.Following
}

func (t *TwitterProfile) GetTweetsCount() *float64 {
	if t == nil {
		return nil
	}
	return t.TweetsCount
}

func (t *TwitterProfile) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TwitterProfile) GetProfileImage() *string {
	if t == nil {
		return nil
	}
	return t.ProfileImage
}

func (t *TwitterProfile) GetBannerImage() *string {
	if t == nil {
		return nil
	}
	return t.BannerImage
}

func (t *TwitterProfile) GetVerified() *bool {
	if t == nil {
		return nil
	}
	return t.Verified
}

func (t *TwitterProfile) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.ExtraProperties
}

func (t *TwitterProfile) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetID(id *string) {
	t.ID = id
	t.require(twitterProfileFieldID)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetUsername(username *string) {
	t.Username = username
	t.require(twitterProfileFieldUsername)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetName(name *string) {
	t.Name = name
	t.require(twitterProfileFieldName)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetCreatedAt(createdAt *string) {
	t.CreatedAt = createdAt
	t.require(twitterProfileFieldCreatedAt)
}

// SetFollowers sets the Followers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetFollowers(followers *float64) {
	t.Followers = followers
	t.require(twitterProfileFieldFollowers)
}

// SetFollowing sets the Following field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetFollowing(following *float64) {
	t.Following = following
	t.require(twitterProfileFieldFollowing)
}

// SetTweetsCount sets the TweetsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetTweetsCount(tweetsCount *float64) {
	t.TweetsCount = tweetsCount
	t.require(twitterProfileFieldTweetsCount)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetDescription(description *string) {
	t.Description = description
	t.require(twitterProfileFieldDescription)
}

// SetProfileImage sets the ProfileImage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetProfileImage(profileImage *string) {
	t.ProfileImage = profileImage
	t.require(twitterProfileFieldProfileImage)
}

// SetBannerImage sets the BannerImage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetBannerImage(bannerImage *string) {
	t.BannerImage = bannerImage
	t.require(twitterProfileFieldBannerImage)
}

// SetVerified sets the Verified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterProfile) SetVerified(verified *bool) {
	t.Verified = verified
	t.require(twitterProfileFieldVerified)
}

func (t *TwitterProfile) UnmarshalJSON(data []byte) error {
	type embed TwitterProfile
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TwitterProfile(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.ExtraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TwitterProfile) MarshalJSON() ([]byte, error) {
	type embed TwitterProfile
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, t.ExtraProperties)
}

func (t *TwitterProfile) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	twitterResponseFieldStatus              = big.NewInt(1 << 0)
	twitterResponseFieldProfile             = big.NewInt(1 << 1)
	twitterResponseFieldRecentTweetsScraped = big.NewInt(1 << 2)
	twitterResponseFieldAiAnalysis          = big.NewInt(1 << 3)
)

type TwitterResponse struct {
	// `success`.
	Status  *string         `json:"status,omitempty" url:"status,omitempty"`
	Profile *TwitterProfile `json:"profile,omitempty" url:"profile,omitempty"`
	// How many recent posts the summary is based on.
	RecentTweetsScraped *float64 `json:"recent_tweets_scraped,omitempty" url:"recent_tweets_scraped,omitempty"`
	// The automated summary (interests, language, likely region, tone, activity pattern, authenticity estimate). Empty when no summary could be made.
	AiAnalysis map[string]any `json:"ai_analysis,omitempty" url:"ai_analysis,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (t *TwitterResponse) GetStatus() *string {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TwitterResponse) GetProfile() *TwitterProfile {
	if t == nil {
		return nil
	}
	return t.Profile
}

func (t *TwitterResponse) GetRecentTweetsScraped() *float64 {
	if t == nil {
		return nil
	}
	return t.RecentTweetsScraped
}

func (t *TwitterResponse) GetAiAnalysis() map[string]any {
	if t == nil {
		return nil
	}
	return t.AiAnalysis
}

func (t *TwitterResponse) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.ExtraProperties
}

func (t *TwitterResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterResponse) SetStatus(status *string) {
	t.Status = status
	t.require(twitterResponseFieldStatus)
}

// SetProfile sets the Profile field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterResponse) SetProfile(profile *TwitterProfile) {
	t.Profile = profile
	t.require(twitterResponseFieldProfile)
}

// SetRecentTweetsScraped sets the RecentTweetsScraped field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterResponse) SetRecentTweetsScraped(recentTweetsScraped *float64) {
	t.RecentTweetsScraped = recentTweetsScraped
	t.require(twitterResponseFieldRecentTweetsScraped)
}

// SetAiAnalysis sets the AiAnalysis field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TwitterResponse) SetAiAnalysis(aiAnalysis map[string]any) {
	t.AiAnalysis = aiAnalysis
	t.require(twitterResponseFieldAiAnalysis)
}

func (t *TwitterResponse) UnmarshalJSON(data []byte) error {
	type embed TwitterResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TwitterResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.ExtraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TwitterResponse) MarshalJSON() ([]byte, error) {
	type embed TwitterResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, t.ExtraProperties)
}

func (t *TwitterResponse) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
