// Code generated by Fern. DO NOT EDIT.

package machineviewer

import (
	context "context"
	io "io"
	os "os"

	osintcat "github.com/OsintCatHQ/osintcat-go"
	core "github.com/OsintCatHQ/osintcat-go/core"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	option "github.com/OsintCatHQ/osintcat-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("OSINTCAT_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// How many machines, files, passwords, tokens, cookies and payment cards the Machine Viewer holds.
//
// Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
func (c *Client) Stats(
	ctx context.Context,
	opts ...option.RequestOption,
) (*osintcat.MachineViewerStats, error) {
	response, err := c.WithRawResponse.Stats(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Searches machines by name, username, hostname or machine ID.
//
// Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
func (c *Client) Search(
	ctx context.Context,
	request *osintcat.SearchMachineViewerRequest,
	opts ...option.RequestOption,
) (*osintcat.MachineSearchResponse, error) {
	response, err := c.WithRawResponse.Search(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// One machine, with the e-mail addresses and tokens found on it.
//
// Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
func (c *Client) Machine(
	ctx context.Context,
	request *osintcat.MachineMachineViewerRequest,
	opts ...option.RequestOption,
) (*osintcat.MachineInfoResponse, error) {
	response, err := c.WithRawResponse.Machine(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Every file of a machine, with its path and size. Use a file's `id` with `machineViewer.file`.
//
// Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
func (c *Client) Files(
	ctx context.Context,
	request *osintcat.FilesMachineViewerRequest,
	opts ...option.RequestOption,
) (*osintcat.MachineFilesResponse, error) {
	response, err := c.WithRawResponse.Files(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// One file, with its content as text.
//
// Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
func (c *Client) File(
	ctx context.Context,
	request *osintcat.FileMachineViewerRequest,
	opts ...option.RequestOption,
) (*osintcat.MachineFileResponse, error) {
	response, err := c.WithRawResponse.File(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The file itself, as it was in the log.
//
// Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
func (c *Client) DownloadFile(
	ctx context.Context,
	request *osintcat.DownloadFileMachineViewerRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.DownloadFile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Every file of a machine in one ZIP archive.
//
// Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
func (c *Client) DownloadMachine(
	ctx context.Context,
	request *osintcat.DownloadMachineMachineViewerRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.DownloadMachine(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
