// Code generated by Fern. DO NOT EDIT.

package account

import (
	context "context"
	os "os"

	osintcat "github.com/OsintCatHQ/osintcat-go"
	core "github.com/OsintCatHQ/osintcat-go/core"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	option "github.com/OsintCatHQ/osintcat-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("OSINTCAT_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns the account the API key belongs to: plan, plan expiry, and how many lookups are left today.
//
// Does not count as a lookup.
//
// Needs the `account:read` scope (keys with all scopes have it).
//
// Errors:
// - 401 `API key required`: No `X-API-KEY` header.
// - 403 `Invalid API key`: The key does not exist or was revoked.
// - 403 `insufficient_scope`: The key lacks the `account:read` scope.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/user
func (c *Client) Get(
	ctx context.Context,
	opts ...option.RequestOption,
) (*osintcat.UserResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Lists every module with its current state and whether your account can use it. Use it to check access before calling a lookup: a lookup for a module your plan does not include is refused with `403 ACCESS_DENIED`.
//
// Does not count as a lookup.
//
// Needs the `osint:read` scope.
//
// Errors:
// - 401 `Unauthorized`: Missing or unknown key.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/modules
func (c *Client) Modules(
	ctx context.Context,
	opts ...option.RequestOption,
) (*osintcat.ModulesResponse, error) {
	response, err := c.WithRawResponse.Modules(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
