// Code generated by Fern. DO NOT EDIT.

package phone

import (
	context "context"
	os "os"

	osintcat "github.com/OsintCatHQ/osintcat-go"
	core "github.com/OsintCatHQ/osintcat-go/core"
	internal "github.com/OsintCatHQ/osintcat-go/internal"
	option "github.com/OsintCatHQ/osintcat-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("OSINTCAT_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns what is known about a phone number: whether it is valid, the carrier and line type, the country, linked online accounts and a risk score.
//
// Counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, the lookup can continue at a per-lookup price charged to your balance (the module's page in the dashboard shows the price); a lookup that finds nothing is not charged.
//
// Errors:
// - 400 `phone_*`: The number cannot be a valid phone number; `code` says why (e.g. `phone_too_short`).
// - 424 `Upstream provider error`: The lookup could not be completed.
// - 424 `The request timed out.`: The lookup took too long.
//
// Docs: https://docs.osintcat.net/api-reference/endpoint/phone-osint
func (c *Client) Lookup(
	ctx context.Context,
	request *osintcat.LookupPhoneRequest,
	opts ...option.RequestOption,
) (*osintcat.PhoneOsintResponse, error) {
	response, err := c.WithRawResponse.Lookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
